/* ============================================================================
   Good Loop — legal texts, PORTUGUESE (pt-BR) — PRIMEIRA VERSÃO

   Block-for-block rendering of legal-en.ts (the working master) in Brazilian
   Portuguese. Part VI.4 of the Terms deliverable: the Portuguese version is
   the GOVERNING one in Brazil and must be prepared through counsel qualified
   there. This draft exists so that no person meets an English legal sentence
   in a Portuguese interface and so that counsel has a concrete text to
   correct; it is not that review. Clauses 16 and 20 are not translations of
   the English clause but the Annex I text, as Part VI.4 requires.

   Register: "você". "Sessão", never "atendimento", "acompanhamento" or
   "acolhimento"; "bem-estar" deliberately (Lexicon_Notes 5, 6, 13, 19).
   ============================================================================ */

import type { LegalDocText } from './types'

export const LEGAL_PT: Record<string, LegalDocText> = {
  'D-01': {
    id: 'D-01',
    title: 'Importante — leia antes de usar o Good Loop',
    blocks: [
      { kind: 'p', text: 'O Good Loop é uma plataforma digital para o bem-estar psicológico. Ele é oferecido de duas formas distintas, e os seus direitos e as nossas responsabilidades mudam conforme a forma que se aplica a você.' },
      { kind: 'p', text: 'Quando você usa o Good Loop sozinho, sem um profissional guiando você, o Good Loop é um serviço de bem-estar. Ele se destina a relaxamento, autoconhecimento e aprendizado sobre bem-estar psicológico. Não é tratamento, não é terapia e não avalia, diagnostica nem maneja nenhuma condição de saúde.' },
      { kind: 'p', text: 'Quando um profissional habilitado usa o Good Loop para guiar você, é esse profissional — e não o Good Loop — quem presta o serviço psicológico a você. O profissional é responsável pelas decisões clínicas tomadas, pela adequação da abordagem à sua situação e pelas suas próprias obrigações profissionais e éticas. O Good Loop fornece a tecnologia, a metodologia e o ambiente em que esse serviço é prestado.' },
      { kind: 'p', text: 'O Good Loop não é um serviço de emergência e nunca deve ser usado em uma emergência. Se você está em risco, ou acredita que outra pessoa está, pare e procure ajuda imediata — veja o nosso Aviso sobre crise e emergência.' },
      { kind: 'p', text: 'Os seguintes avisos fazem parte destes Termos e se aplicam ao seu uso do Good Loop: o Aviso sobre a natureza do serviço; o Aviso sobre crise e emergência; o Aviso sobre uso por conta própria; o Aviso sobre uso guiado por profissional; o Aviso sobre recursos automatizados; o Aviso sobre confidencialidade e dados; e os demais avisos publicados na nossa página de informações legais. Por favor, leia-os. Havendo conflito entre o resumo de um aviso e o seu texto integral, prevalece o texto integral.' },
      { kind: 'p', text: 'Se você não concorda com estes avisos, por favor não use o Good Loop.' },
    ],
  },
  'D-02': {
    id: 'D-02',
    title: 'Natureza do serviço e finalidade de uso',
    blocks: [
      { kind: 'h', text: 'Finalidade de uso' },
      { kind: 'p', text: 'O software do Good Loop fornece conteúdo em áudio pré-gravado e ferramentas de organização de sessões a adultos com dezoito anos ou mais, de duas formas: (i) como recurso de bem-estar para uso por conta própria, com conteúdo de relaxamento, autoconhecimento e psicoeducação; e (ii) como biblioteca de conteúdo e ferramentas da qual um profissional habilitado seleciona de forma independente, e que esse profissional pode usar dentro de um cuidado que ele planeja, presta e pelo qual permanece clinicamente responsável.' },
      { kind: 'h', text: 'O que o Good Loop não é' },
      { kind: 'p', text: 'O Good Loop não é um dispositivo médico. Ele não diagnostica, não trata, não cura, não previne, não monitora nem prevê nenhuma doença, transtorno ou condição clínica. Ele não determina, nem pretende determinar, se você tem alguma condição, qual a sua gravidade ou qual cuidado você deveria receber. Ele não seleciona, sequencia, recomenda nem adapta conteúdo com base em nada a seu respeito. O Good Loop não prescreve e não dá nenhuma orientação sobre medicamentos; se algo na plataforma parecer fazer isso, desconsidere e nos avise.' },
      { kind: 'p', text: 'O Good Loop não substitui orientação, diagnóstico ou tratamento médico, psiquiátrico ou psicológico profissional. Procure sempre a orientação de um profissional de saúde qualificado para qualquer dúvida sobre a sua saúde ou a sua saúde mental. Nunca desconsidere uma orientação profissional, nem adie procurá-la, por causa de algo que você leu, viu ou fez no Good Loop. Nunca inicie, interrompa ou altere um medicamento por causa do Good Loop.' },
      { kind: 'p', text: 'O Good Loop não é adequado, e não é oferecido, para uso em crise de saúde mental, em emergência ou em situação de risco para você ou para qualquer outra pessoa. O Good Loop não é adequado para pessoas com doença mental grave ou persistente que precisam de cuidado especializado, e não foi projetado para uso onde é necessária avaliação clínica presencial.' },
      { kind: 'p', text: 'O Good Loop não deve ser usado para obter qualquer determinação, certificação, laudo ou documentação oficial — inclusive para fins judiciais, trabalhistas, securitários, migratórios ou previdenciários — e nenhum resultado da plataforma deve ser apresentado ou usado para tal fim.' },
      { kind: 'h', text: 'Como o nosso conteúdo é organizado' },
      { kind: 'p', text: 'As nossas sessões são agrupadas pela situação em que você pode estar — um dia de trabalho, uma viagem, o fim de uma noite — para que você encontre uma que combine com o momento. Esse agrupamento descreve uma circunstância e nada mais. Não é uma indicação, não é uma afirmação sobre nenhuma condição, e nenhuma sessão é oferecida a você com base em algo que sabemos ou supomos sobre a sua saúde.' },
      { kind: 'h', text: 'Para quem é' },
      { kind: 'p', text: 'O Good Loop é oferecido a adultos com dezoito anos ou mais, nos territórios em que declaramos que ele está disponível. Não é oferecido a crianças ou adolescentes.' },
    ],
  },
  'D-03-BR': {
    id: 'D-03-BR',
    title: 'Se você está em risco, não use o Good Loop — busque ajuda agora',
    blocks: [
      { kind: 'p', text: 'O Good Loop não é um serviço de emergência, não é monitorado em tempo real e não pode ajudar você em uma crise.' },
      { kind: 'p', text: 'Se você está pensando em tirar a própria vida, em machucar a si mesmo ou a outra pessoa, ou se acredita que você ou qualquer outra pessoa está em perigo, pare de usar o Good Loop e busque ajuda imediatamente:' },
      { kind: 'p', text: 'Apoio emocional e prevenção do suicídio — CVV: ligue 188 (gratuito, 24 horas) ou acesse cvv.org.br' },
      { kind: 'p', text: 'Emergência médica — SAMU: ligue 192. Polícia e emergência geral: ligue 190.' },
      { kind: 'p', text: 'Ou vá ao pronto-socorro do hospital mais próximo, ou a uma UPA ou a um CAPS perto de você.' },
      { kind: 'p', text: 'Se você está com alguém em risco, não deixe a pessoa sozinha e peça ajuda.' },
      { kind: 'p', text: 'Nada no Good Loop — inclusive qualquer mensagem que você envie dentro da plataforma, a um profissional ou a qualquer recurso automatizado — será tratado como pedido de socorro, e nenhuma mensagem desse tipo produzirá uma resposta de emergência. As mensagens enviadas a um profissional não são lidas em tempo real e podem só ser vistas no próximo período de trabalho desse profissional.' },
    ],
  },
  'D-03-EU': {
    id: 'D-03-EU',
    title: 'Se você está em risco, não use o Good Loop — busque ajuda agora',
    blocks: [
      { kind: 'p', text: 'O Good Loop não é um serviço de emergência, não é monitorado em tempo real e não pode ajudar você em uma crise.' },
      { kind: 'p', text: 'Se você está pensando em tirar a própria vida, em machucar a si mesmo ou a outra pessoa, ou se acredita que você ou qualquer outra pessoa está em perigo, pare de usar o Good Loop e busque ajuda imediatamente:' },
      { kind: 'p', text: 'Serviços de emergência — ligue 112, o número único europeu de emergência, gratuito de qualquer telefone.' },
      { kind: 'p', text: 'Ou vá ao pronto-socorro do hospital mais próximo.' },
      { kind: 'p', text: '[Inserir aqui a linha nacional verificada de apoio emocional e prevenção para cada país em que o serviço é oferecido, com nome, número, horários e site.]' },
      { kind: 'p', text: 'Se você está com alguém em risco, não deixe a pessoa sozinha e peça ajuda.' },
      { kind: 'p', text: 'Nada no Good Loop — inclusive qualquer mensagem que você envie dentro da plataforma, a um profissional ou a qualquer recurso automatizado — será tratado como pedido de socorro, e nenhuma mensagem desse tipo produzirá uma resposta de emergência.' },
    ],
  },
  'D-04': {
    id: 'D-04',
    title: 'Quando você usa o Good Loop por conta própria',
    blocks: [
      { kind: 'p', text: 'Você está usando o Good Loop por conta própria sempre que acessa os seus conteúdos, exercícios ou ferramentas sem um profissional habilitado guiando esse uso. Boa parte do que segue é bom senso, mas importa, e queremos ser claros.' },
      { kind: 'h', text: 'Para que serve o uso por conta própria' },
      { kind: 'p', text: 'Relaxar. Descansar. Perceber como você se sente e refletir sobre isso. Aprender sobre bem-estar psicológico em termos gerais. Construir hábitos do dia a dia que muitas pessoas consideram úteis. É só isso, e para muitas pessoas é genuinamente útil.' },
      { kind: 'h', text: 'O que o uso por conta própria não é' },
      { kind: 'p', text: 'Não é terapia. Não é tratamento. Não é uma intervenção clínica, e não é um curso de cuidado. Nada do que você faz sozinho no Good Loop é direcionado a uma condição que você possa ter, porque o Good Loop não sabe e não tenta determinar se você tem alguma. Nenhum exercício, técnica ou conteúdo oferecido a você no uso por conta própria foi selecionado por causa de uma avaliação da sua saúde.' },
      { kind: 'p', text: 'A Metodologia GL é uma metodologia psicológica. No uso por conta própria, você recebe conteúdo geral de bem-estar inspirado nela. Você não está recebendo a Metodologia como tratamento, porque a Metodologia só é aplicada como tratamento por um profissional qualificado que conhece a sua situação e assume a responsabilidade por essa aplicação.' },
      { kind: 'h', text: 'Por que as sessões são agrupadas por situação' },
      { kind: 'p', text: 'Algumas sessões são feitas para um momento específico — antes de um voo, entre reuniões, no fim do dia. Isso porque o relaxamento funciona melhor quando se encaixa nas circunstâncias em que você realmente está: quanto tempo você tem, se pode fechar os olhos, se está sentado em um espaço apertado. Agrupar as sessões assim diz respeito ao momento, não a você. Não significa que achamos que você tem alguma condição, e escolher uma sessão não nos diz nada sobre a sua saúde.' },
      { kind: 'h', text: 'Se você precisa de mais do que isso' },
      { kind: 'p', text: 'Se você está passando por dificuldades, se algo não melhora ou se não tem certeza de que o uso por conta própria é suficiente para você, fale com um profissional qualificado. Você pode organizar um apoio guiado por profissional pelo Good Loop, onde isso estiver disponível para você, ou buscar ajuda por conta própria. Por favor, não use o conteúdo por conta própria como motivo para adiar uma ajuda de que você pode precisar.' },
    ],
  },
  'D-05': {
    id: 'D-05',
    title: 'Quando um profissional guia o seu uso do Good Loop',
    blocks: [
      { kind: 'p', text: 'Quando um profissional habilitado trabalha com você pelo Good Loop, o serviço psicológico é prestado a você por esse profissional. O profissional é independente. O Good Loop fornece conteúdo em áudio e as ferramentas para organizar sessões; o profissional decide o que é usado, quando, e se serve para você. O Good Loop não presta o serviço psicológico, não participa do seu cuidado e não recomenda, sequencia nem adapta nada para você.' },
      { kind: 'h', text: 'Pelo que o profissional é responsável' },
      { kind: 'p', text: 'O profissional é responsável por decidir se trabalhar com você a distância é adequado à sua situação; pelo julgamento clínico exercido no seu caso; por selecionar, adaptar e aplicar a Metodologia GL ou qualquer outra abordagem a você; por manter o registro profissional exigido pelo seu conselho; pelo seu próprio sigilo profissional; e por cumprir as normas do conselho profissional em que está registrado. Essas decisões são dele, e o Good Loop não as toma nem as anula.' },
      { kind: 'h', text: 'Pelo que o Good Loop é responsável' },
      { kind: 'p', text: 'O Good Loop é responsável pelo funcionamento da plataforma conforme descrito, por o conteúdo ser como o descrevemos, por verificar — no ingresso e periodicamente depois — que cada profissional mantém registro ativo no conselho profissional competente, e pela segurança do ambiente. O Good Loop não é responsável pelo conteúdo clínico, pela qualidade ou pelo resultado do que um profissional decide no seu caso — inclusive qual conteúdo ele escolhe e como o usa.' },
      { kind: 'h', text: 'O que não verificamos' },
      { kind: 'p', text: 'Verificamos o registro profissional. Não garantimos a competência clínica de nenhum profissional, a sua adequação a você ou o resultado de trabalhar com ele. Se um profissional não é o certo para você, nos avise e ajudaremos a trocar; se acredita que um profissional agiu de forma inadequada, nos avise e você também pode reclamar ao conselho profissional dele, cujos contatos forneceremos.' },
      { kind: 'h', text: 'O seu acordo com o profissional' },
      { kind: 'p', text: 'A sua relação com o profissional é regida pelo consentimento informado e por quaisquer condições de serviço acordadas diretamente entre você e ele, além destes Termos. Onde esses documentos tratam da relação clínica, eles prevalecem sobre estes Termos nesse assunto.' },
    ],
  },
  'D-06': {
    id: 'D-06',
    title: 'Recursos automatizados e inteligência artificial',
    blocks: [
      { kind: 'p', text: 'O Good Loop atualmente não usa inteligência artificial. Nenhuma parte do Good Loop é gerada, selecionada ou avaliada por um sistema de IA, e nenhuma decisão que afete você é tomada por meios automatizados.' },
      { kind: 'p', text: 'Não inferimos as suas emoções ou intenções a partir do seu rosto, da sua voz ou de qualquer outra característica.' },
      { kind: 'p', text: 'Não usamos o seu conteúdo para treinar modelos de inteligência artificial, e não permitimos que nenhum dos nossos fornecedores o faça.' },
      { kind: 'p', text: 'Se introduzirmos recursos que usem inteligência artificial, avisaremos com antecedência, os identificaremos claramente onde quer que apareçam e publicaremos uma versão atualizada deste aviso antes de entrarem em operação.' },
    ],
  },
  'D-07': {
    id: 'D-07',
    title: 'Independência profissional',
    blocks: [
      { kind: 'p', text: 'Os profissionais que trabalham pelo Good Loop exercem julgamento profissional independente. O Good Loop não dirige, instrui, revisa, anula nem questiona as decisões clínicas de um profissional, e não exige que um profissional aplique a Metodologia GL, ou qualquer técnica específica dela, a nenhuma pessoa.' },
      { kind: 'p', text: 'O conselho do profissional exige que ele avalie se determinada abordagem e determinado formato são adequados à pessoa à sua frente, e que recuse ou encaminhe quando não são. Nada na plataforma, nos materiais, na formação ou nos acordos comerciais do Good Loop afasta esse dever, e qualquer sugestão, recomendação ou indicação gerada pela plataforma é meramente orientativa e pode ser desconsiderada pelo profissional a seu critério.' },
      { kind: 'p', text: 'O Good Loop não emprega os profissionais que prestam serviços psicológicos pela plataforma, salvo quando declararmos expressamente o contrário por escrito, e estes Termos não criam nenhuma relação de agência, sociedade ou emprego.' },
      { kind: 'p', text: 'O Good Loop não recomenda conteúdo, não sugere ordem de uso, não gera plano e não varia o que está disponível conforme nada a respeito de uma pessoa. A biblioteca é a mesma para todos os profissionais. Seleção, ordem, momento e interpretação são decisões exclusivas do profissional.' },
    ],
  },
  'D-08': {
    id: 'D-08',
    title: 'O que o seu empregador nunca verá',
    blocks: [
      { kind: 'p', text: 'O seu empregador, ou qualquer organização que pague o seu acesso ao Good Loop, comprou um serviço para você. Não comprou informações sobre você. Este aviso explica exatamente o que essa organização pode e não pode saber, e é um compromisso vinculante, não uma declaração de intenção.' },
      { kind: 'p', text: 'O seu patrocinador nunca receberá, e nós nunca lhe revelaremos:' },
      { kind: 'p', text: 'se você usou o Good Loop; quando ou com que frequência o usou; qual conteúdo você viu ou quais exercícios fez; qualquer coisa que você escreveu, gravou ou inseriu; se você agendou, compareceu ou faltou a uma sessão; a identidade de qualquer profissional com quem trabalhou; qualquer coisa discutida em uma sessão; qualquer avaliação, anotação, registro ou observação sobre você; ou qualquer informação a partir da qual algo disso possa razoavelmente ser deduzido.' },
      { kind: 'h', text: 'O que o seu patrocinador recebe' },
      { kind: 'p', text: 'O seu patrocinador recebe informações sobre o programa, não sobre pessoas: números agregados de adesão e uso gerais em toda a sua população, e relatórios gerais sobre o serviço. Todo esse relatório é agregado e desidentificado, e não publicamos nenhum número derivado de um grupo com menos de [vinte e cinco] pessoas. Quando um grupo é menor que esse limite, o número é suprimido em vez de informado.' },
      { kind: 'h', text: 'Sessões e informações clínicas' },
      { kind: 'p', text: 'Quando um profissional guia o seu uso do Good Loop, o que se passa entre você e esse profissional está coberto pelo sigilo profissional. Não está disponível ao seu patrocinador de nenhuma forma, em nenhuma circunstância, e nenhum contrato entre o Good Loop e o seu patrocinador lhe dá qualquer direito sobre isso.' },
      { kind: 'h', text: 'As obrigações do seu patrocinador com você' },
      { kind: 'p', text: 'O nosso acordo com o seu patrocinador exige que ele não nos peça informações individuais sobre você, não peça que você revele o seu uso do Good Loop e não trate você de forma diferente por ter usado o Good Loop ou por não ter usado. Se você acredita que isso aconteceu, nos avise pelos contatos indicados nos nossos Termos.' },
      { kind: 'h', text: 'Fim ou mudança do seu acesso patrocinado' },
      { kind: 'p', text: 'Se o seu patrocinador deixar de pagar, ou se você sair da organização, avisaremos antes que o seu acesso mude e explicaremos o que acontece com as suas informações e como você pode continuar por conta própria, onde essa opção estiver disponível.' },
    ],
  },
  'D-09': {
    id: 'D-09',
    title: 'O Good Loop e as suas obrigações como empregador',
    blocks: [
      { kind: 'p', text: 'O Good Loop é um serviço de bem-estar oferecido às suas pessoas. Não é um produto de conformidade e não cumpre nenhuma obrigação legal que recaia sobre você.' },
      { kind: 'p', text: 'Em particular, e sem limitação: fornecer o Good Loop não identifica, avalia, estima, documenta nem gerencia os fatores de risco psicossociais presentes na sua organização; não constitui nem contribui para nenhum inventário de riscos, programa de gerenciamento de riscos, plano de ação ou avaliação de riscos que você seja obrigado a elaborar; não satisfaz nenhuma obrigação que você possa ter em relação a saúde e segurança do trabalho, condições de trabalho ou organização do trabalho; e não é prova de que tal obrigação tenha sido cumprida.' },
      { kind: 'p', text: 'Obrigações desse tipo dizem respeito às condições e à organização do trabalho na sua empresa. São suas. Não são transferidas ao Good Loop por nenhum acordo entre nós, e o Good Loop não assume nenhuma delas.' },
      { kind: 'p', text: 'O Good Loop pode fazer parte do apoio que você escolhe oferecer às suas pessoas, e oferecer um apoio desse tipo pode ser um entre muitos elementos de como você lida com o bem-estar no trabalho. Se é suficiente, e o que mais você deve fazer, são questões suas e dos seus consultores.' },
      { kind: 'p', text: 'O Good Loop não realiza avaliações clínicas individuais dos seus colaboradores e não fornece a você informações sobre nenhum indivíduo. Nada no serviço foi projetado ou se destina a ser usado como mecanismo de avaliação de risco psicossocial na sua organização.' },
    ],
  },
  'D-10': {
    id: 'D-10',
    title: 'Confidencialidade, as suas informações e segurança',
    blocks: [
      { kind: 'h', text: 'Confidencialidade' },
      { kind: 'p', text: 'O que você conta a um profissional pelo Good Loop é confidencial e está protegido pelo sigilo profissional a que esse profissional está sujeito pelas normas da sua profissão. O Good Loop trata as informações sobre o seu uso da plataforma como confidenciais e só as revela conforme descrito no nosso Aviso de Privacidade.' },
      { kind: 'h', text: 'Os limites da confidencialidade' },
      { kind: 'p', text: 'A confidencialidade não é absoluta. Um profissional pode ser obrigado por lei ou pelas normas da sua profissão a revelar informações em circunstâncias restritas — por exemplo, quando há risco grave e iminente à sua vida ou à vida de outra pessoa, quando uma criança ou uma pessoa em risco precisa de proteção, ou quando um tribunal ou autoridade competente exige legalmente a revelação. O seu profissional explicará esses limites a você como parte do consentimento informado, e avisará sempre que for possível e apropriado.' },
      { kind: 'h', text: 'Gravação' },
      { kind: 'p', text: 'Você não deve gravar, fotografar, capturar a tela ou de outra forma registrar nenhuma sessão, e não deve compartilhar nenhuma gravação desse tipo. Os profissionais estão sujeitos à mesma regra e só podem gravar com o seu consentimento separado, específico e documentado, onde as suas normas profissionais permitirem.' },
      { kind: 'h', text: 'Segurança' },
      { kind: 'p', text: 'Levamos a sério a segurança das suas informações e aplicamos medidas técnicas e organizacionais adequadas à sua sensibilidade, incluindo criptografia em trânsito e em repouso, controles de acesso que limitam quem no Good Loop pode ver o quê, registro de acessos e revisões regulares. Trabalhamos apenas com fornecedores que atendem aos padrões que exigimos.' },
      { kind: 'p', text: 'Nenhum sistema conectado à internet pode ter garantia de segurança perfeita, e não podemos prometer isso. O que prometemos é que manteremos uma proteção adequada, que avisaremos você e a autoridade competente se um incidente de segurança afetar as suas informações de forma que exija notificação, e que diremos a você o que aconteceu e o que estamos fazendo a respeito.' },
      { kind: 'h', text: 'A sua parte' },
      { kind: 'p', text: 'Por favor, mantenha as suas credenciais de acesso em segredo, não compartilhe a sua conta e use o Good Loop em um lugar reservado onde você possa falar livremente e onde outras pessoas não possam ouvir ou ver a sua tela. Avise-nos imediatamente se achar que outra pessoa acessou a sua conta.' },
    ],
  },
  'D-11': {
    id: 'D-11',
    title: 'Idade',
    blocks: [
      { kind: 'p', text: 'O Good Loop é oferecido apenas a pessoas com dezoito anos ou mais. Não foi projetado para crianças ou adolescentes, não é oferecido a eles, não é adequado a eles e não é divulgado para eles.' },
      { kind: 'p', text: 'Ao usar o Good Loop, você confirma que tem dezoito anos ou mais e que tem capacidade legal para aceitar estes Termos.' },
      { kind: 'p', text: 'Se soubermos que uma pessoa menor de dezoito anos criou uma conta, suspenderemos a conta, excluiremos os dados pessoais que mantemos sobre essa pessoa, exceto onde a lei nos obrigar a mantê-los, e, quando as circunstâncias exigirem, tomaremos as medidas apropriadas em relação à segurança dessa pessoa.' },
    ],
  },
  'D-12': {
    id: 'D-12',
    title: 'Onde o Good Loop é oferecido',
    blocks: [
      { kind: 'p', text: 'O Good Loop é oferecido apenas nos territórios listados no nosso site. Não oferecemos o Good Loop, nem o direcionamos, a pessoas em qualquer outro território.' },
      { kind: 'p', text: 'Os serviços guiados por profissional estão sujeitos a uma restrição adicional. Um profissional só pode trabalhar com você pelo Good Loop se estiver registrado e autorizado a exercer no território que se aplica à sua situação, e apenas a partir de um local de onde ele tenha permissão para exercer. Onde as normas profissionais aplicáveis exigirem que o profissional esteja fisicamente presente em determinado território, ou opere a partir de uma conexão nele registrada, o profissional deve cumprir essa exigência.' },
      { kind: 'p', text: 'Se você se mudar para um território em que não oferecemos o serviço, ou acessar o Good Loop a partir dele, alguns ou todos os recursos podem ficar indisponíveis, e os serviços guiados por profissional em particular podem ser suspensos até que a situação seja esclarecida. Isso é uma restrição legal, não uma escolha comercial.' },
      { kind: 'p', text: 'Você é responsável por cumprir a lei do lugar de onde acessa o Good Loop.' },
    ],
  },
  'D-13': {
    id: 'D-13',
    title: 'O que podemos e não podemos prometer',
    blocks: [
      { kind: 'p', text: 'As pessoas respondem de forma diferente ao apoio ao bem-estar psicológico. O que ajuda uma pessoa pode não ajudar outra, e o progresso raramente é linear. Não prometemos nenhum resultado específico do uso do Good Loop, e ninguém pode fazê-lo honestamente.' },
      { kind: 'p', text: 'Comprometemo-nos a prestar o serviço com o cuidado, a competência e a diligência que se pode razoavelmente esperar de um prestador competente de um serviço desse tipo, a descrever com precisão o que oferecemos e a corrigir quando erramos. Não nos comprometemos com nenhuma melhora específica em como você se sente, com nenhum resultado nem com nenhum prazo, e nenhuma declaração feita por nós, por qualquer profissional ou em qualquer dos nossos materiais deve ser entendida como tal compromisso.' },
      { kind: 'p', text: 'Quando um profissional guia o seu uso do Good Loop, a obrigação do profissional é igualmente de cuidado profissional diligente, e não uma garantia de qualquer resultado clínico.' },
    ],
  },
  'D-14': {
    id: 'D-14',
    title: 'Conteúdos e serviços que não controlamos',
    blocks: [
      { kind: 'p', text: 'O Good Loop pode direcionar para, ou trabalhar com, sites, aplicativos, recursos e serviços operados por outras organizações — inclusive provedores de pagamento, ferramentas de comunicação, organizações de apoio e de crise, e conteúdo produzido por terceiros. Não os controlamos e não somos responsáveis por eles, pelo seu conteúdo, pelas suas condições ou por como tratam as suas informações.' },
      { kind: 'p', text: 'Um link não é um endosso, exceto quando dizemos expressamente que é. Antes de usar qualquer serviço de terceiros, leia as suas condições e as suas informações de privacidade.' },
      { kind: 'p', text: 'O Good Loop também pode conter material fornecido por usuários ou por profissionais. Não revisamos tudo o que é fornecido antes de aparecer. Se você encontrar no Good Loop conteúdo ilegal, prejudicial ou contrário às nossas regras, denuncie pelos contatos indicados nos nossos Termos. Avaliaremos toda denúncia que recebermos e, quando for fundamentada, removeremos ou restringiremos o acesso ao conteúdo e diremos a você o que fizemos.' },
    ],
  },
  'D-15': {
    id: 'D-15',
    title: 'Sobre o que dizemos, e o que outros dizem, sobre o Good Loop',
    blocks: [
      { kind: 'p', text: 'Descrevemos o Good Loop como um serviço de bem-estar, porque é isso que ele é. Não afirmamos que o Good Loop trata, cura, previne ou reduz os sintomas de qualquer doença, transtorno ou condição, e qualquer declaração que pareça afirmar isso deve ser desconsiderada e comunicada a nós.' },
      { kind: 'p', text: 'Quando publicamos o relato da experiência de uma pessoa, é a experiência dessa pessoa e nada mais. Experiências individuais não são típicas, não são prova do que acontecerá com qualquer outra pessoa e não são promessa de nenhum resultado. Os depoimentos são publicados com o consentimento da pessoa e podem ser editados para reduzir a extensão; não são pagos, salvo quando dizemos que são.' },
      { kind: 'p', text: 'Quando citamos uma pesquisa, identificamos qual foi a pesquisa, o que ela mediu e quais são os seus limites. Uma pesquisa sobre uma metodologia, uma abordagem ou uma população não é uma afirmação sobre você.' },
      { kind: 'p', text: 'Descrevemos a nossa metodologia como capaz de produzir um relaxamento mais eficiente, e sessões bem adaptadas a situações específicas. São afirmações sobre como a nossa metodologia funciona, e temos as evidências para elas. Não são afirmações de que o Good Loop trata alguma coisa.' },
    ],
  },
  'D-16': {
    id: 'D-16',
    title: 'Propriedade intelectual',
    blocks: [
      { kind: 'p', text: 'A plataforma Good Loop, o seu conteúdo, o seu design, o seu software e a Metodologia GL, junto com todos os materiais, protocolos, exercícios, instrumentos, sequências e documentação que expressam ou incorporam a Metodologia GL, são protegidos por direitos autorais e por outros direitos de propriedade intelectual, e os elementos confidenciais da Metodologia GL são protegidos como segredos de negócio. Pertencem ao Good Loop ou são usados pelo Good Loop sob licença. A Metodologia GL foi criada pelo seu autor intelectual, cuja autoria é reconhecida e preservada.' },
      { kind: 'p', text: 'Você recebe um direito pessoal, limitado, revogável, não exclusivo e intransferível de usar o Good Loop para o seu próprio uso, conforme permitido por estes Termos. Nada é cedido ou licenciado a você além disso.' },
      { kind: 'p', text: 'Você não deve copiar, reproduzir, adaptar, traduzir, publicar, distribuir, vender, sublicenciar, comunicar publicamente ou disponibilizar qualquer parte da plataforma ou da Metodologia GL; não deve fazer engenharia reversa, descompilar ou tentar derivar a estrutura ou a lógica da plataforma ou da Metodologia; não deve usar qualquer parte da plataforma ou da Metodologia para desenvolver, treinar, avaliar ou aprimorar qualquer produto, modelo ou serviço concorrente; e não deve extrair ou raspar conteúdo da plataforma por qualquer meio, automatizado ou não.' },
      { kind: 'p', text: 'Essas restrições continuam a se aplicar depois que você deixa de usar o Good Loop.' },
    ],
  },
  'D-17': {
    id: 'D-17',
    title: 'Avisos no produto — requisito essencial',
    blocks: [
      { kind: 'p', text: 'Toda tela do Good Loop dá acesso com um toque à ajuda de emergência pelo botão Ajuda agora, que mostra os números de emergência antes de qualquer outra coisa.' },
      { kind: 'p', text: 'A biblioteca de uso por conta própria declara em uma linha que as suas sessões são para relaxamento e são agrupadas por momento, e não por condição. Na primeira vez que a pessoa abre cada categoria, uma nota curta reafirma isso e, quando pertinente, indica a ajuda profissional. Toda sessão de uso por conta própria termina com um link para encontrar um profissional.' },
      { kind: 'p', text: 'O texto integral de cada aviso está disponível a um toque de distância e na página de informações legais.' },
      { kind: 'p', text: 'Nenhum aviso é jamais acionado, alterado ou programado com base em algo que a pessoa digitou, escolheu, avaliou ou pelo qual foi avaliada, nem com base em qualquer padrão do seu uso do serviço. Os avisos aparecem em momentos fixos — no ingresso, no pagamento, no agendamento, na primeira visita a uma seção ou em uma data do calendário — nos mesmos termos para todas as pessoas.' },
    ],
  },
  terms: {
    id: 'terms',
    title: 'Termos e condições',
    blocks: [
      { kind: 'p', text: 'Versão [1.0] — em vigor a partir de [data]. Leia estes Termos antes de usar o Good Loop. Eles estabelecem o que nos comprometemos a fazer, o que pedimos a você e o que acontece se algo der errado. Alguns deles limitam o que você pode exigir de nós, e nós os marcamos claramente.' },
      { kind: 'h', text: '1. Quem somos' },
      { kind: 'p', text: '1.1 O Good Loop é operado por [razão social completa], sociedade constituída em [jurisdição] sob o número de registro [•], com sede em [•] («Good Loop», «nós»).' },
      { kind: 'p', text: '1.2 Você pode nos contatar em [email], pela função de suporte na plataforma ou escrevendo para o endereço acima. O nosso encarregado pela proteção de dados pode ser contatado em [email].' },
      { kind: 'h', text: '2. Estes Termos e os documentos que fazem parte deles' },
      { kind: 'p', text: '2.1 Estes Termos são um contrato entre você e nós. Ao criar uma conta, ou ao usar o Good Loop, você os aceita.' },
      { kind: 'p', text: '2.2 Os seguintes documentos fazem parte destes Termos e estão disponíveis na nossa página de informações legais: os Avisos da plataforma (D-01 a D-16), o Aviso de Privacidade e quaisquer condições específicas de produto que apresentarmos a você no momento da compra. Onde o resumo de qualquer um deles divergir do texto integral, prevalece o texto integral.' },
      { kind: 'p', text: '2.3 Se o seu acesso ao Good Loop é pago por um empregador ou outra organização, o Suplemento do usuário final também se aplica a você e, nas questões de patrocínio, prevalece sobre estes Termos.' },
      { kind: 'p', text: '2.4 Nada nestes Termos elimina ou limita um direito que você tenha pela lei de defesa do consumidor do país em que vive. Onde uma disposição destes Termos conflitar com esse direito, aplica-se o direito e a disposição não se aplica.' },
      { kind: 'h', text: '3. Definições' },
      { kind: 'p', text: '3.1 Nestes Termos: «Conteúdo» significa tudo o que é disponibilizado pelo Good Loop; «Metodologia GL» significa a metodologia psicológica proprietária descrita nos nossos materiais, junto com tudo o que a expressa ou incorpora; «Profissional» significa uma pessoa habilitada e registrada para prestar serviços psicológicos que oferece esses serviços pelo Good Loop; «Uso guiado por profissional» significa o uso do Good Loop em que um Profissional dirige a aplicação da Metodologia GL a você; «Uso por conta própria» significa qualquer outro uso; «Serviço» significa a plataforma Good Loop e tudo o que fornecemos por ela; e «Patrocinador» significa uma organização que paga o seu acesso.' },
      { kind: 'h', text: '4. Quem pode usar o Good Loop' },
      { kind: 'p', text: '4.1 Você deve ter dezoito anos ou mais e capacidade legal para aceitar estes Termos. O Good Loop não é oferecido a crianças ou adolescentes.' },
      { kind: 'p', text: '4.2 O Good Loop é oferecido apenas nos territórios listados no nosso site, e o Uso guiado por profissional está sujeito às restrições adicionais do Aviso sobre abrangência territorial (D-12).' },
      { kind: 'p', text: '4.3 Você pode ter apenas uma conta, e ela é pessoal. Você não deve compartilhá-la nem permitir que outra pessoa a use.' },
      { kind: 'h', text: '5. A sua conta' },
      { kind: 'p', text: '5.1 Você deve nos dar informações precisas ao se cadastrar e mantê-las atualizadas. Como o Good Loop diz respeito ao seu bem-estar, informações imprecisas podem levar a um apoio que não se encaixa na sua situação.' },
      { kind: 'p', text: '5.2 Mantenha as suas credenciais em segredo. Avise-nos imediatamente se acreditar que outra pessoa obteve acesso à sua conta, e ajudaremos você a protegê-la.' },
      { kind: 'p', text: '5.3 Podemos exigir verificação adicional quando razoavelmente necessário — por exemplo, para confirmar a elegibilidade ao programa de um Patrocinador.' },
      { kind: 'h', text: '6. O que é o Serviço' },
      { kind: 'p', text: '6.1 O Good Loop é uma plataforma digital para o bem-estar psicológico, oferecida de duas formas distintas descritas nos Avisos da plataforma.' },
      { kind: 'p', text: '6.2 Uso por conta própria. Quando você usa o Good Loop sem um Profissional guiando você, o Serviço é um serviço de bem-estar destinado a relaxamento, autoconhecimento e psicoeducação. Não é tratamento, não é terapia, não diagnostica e não avalia nem maneja nenhuma condição de saúde. Veja D-02 e D-04.' },
      { kind: 'p', text: '6.3 Uso guiado por profissional. Quando um Profissional trabalha com você pelo Good Loop, esse Profissional presta o serviço psicológico a você e detém a relação clínica. Nós fornecemos a plataforma, a Metodologia GL e o ambiente. Veja D-05 e D-07.' },
      { kind: 'p', text: '6.4 Não é um serviço de emergência. O Good Loop não é monitorado em tempo real e nunca deve ser usado em uma emergência ou quando alguém está em risco. Veja D-03.' },
      { kind: 'p', text: '6.5 O Good Loop atualmente não inclui recursos que usem inteligência artificial. Se os introduzirmos, avisaremos com antecedência e o Aviso sobre recursos automatizados (D-06) explicará como funcionam.' },
      { kind: 'h', text: '7. Licença e propriedade intelectual' },
      { kind: 'p', text: '7.1 Concedemos a você um direito pessoal, limitado, revogável, não exclusivo e intransferível de usar o Serviço e acessar o Conteúdo para o seu próprio uso, de acordo com estes Termos. Esse direito termina quando o seu acesso termina.' },
      { kind: 'p', text: '7.2 Todos os direitos sobre o Serviço, o Conteúdo e a Metodologia GL permanecem conosco ou com os nossos licenciantes, conforme o Aviso sobre propriedade intelectual (D-16). Nada nestes Termos transfere qualquer deles a você.' },
      { kind: 'p', text: '7.3 Você não deve copiar, adaptar, distribuir, vender, sublicenciar ou publicar qualquer parte do Serviço ou da Metodologia GL; não deve fazer engenharia reversa ou tentar derivar a sua estrutura ou lógica; não deve usar qualquer parte deles para desenvolver, treinar, avaliar ou aprimorar qualquer produto, modelo ou serviço concorrente; e não deve extrair ou raspar Conteúdo por qualquer meio. Essas restrições sobrevivem ao término.' },
      { kind: 'p', text: '7.4 Se você contribuir com algo para o Serviço — uma anotação, uma mensagem, um feedback — você mantém os seus direitos sobre isso. Você nos concede uma licença para hospedar, armazenar, transmitir e exibir esse conteúdo estritamente conforme necessário para operar o Serviço para você e conforme descrito no nosso Aviso de Privacidade. Não usamos o conteúdo das suas sessões com um Profissional, nem informações clínicas sobre você, para treinar modelos de inteligência artificial.' },
      { kind: 'p', text: '7.5 Quando você nos dá feedback sobre o Serviço, podemos usá-lo livremente para melhorar o Serviço, sem obrigação para com você.' },
      { kind: 'h', text: '8. Uso aceitável' },
      { kind: 'p', text: '8.1 Você deve usar o Good Loop de forma lícita, respeitosa e para a finalidade a que se destina. Em particular, você não deve:' },
      { kind: 'li', text: '(a) usar o Serviço para obter diagnóstico, prescrição, certificação ou qualquer determinação oficial;' },
      { kind: 'li', text: '(b) se passar por outra pessoa, ou falsear a sua identidade, idade ou elegibilidade;' },
      { kind: 'li', text: '(c) gravar, fotografar, capturar a tela ou de outra forma registrar uma sessão, ou compartilhar tal gravação;' },
      { kind: 'li', text: '(d) assediar, ameaçar, abusar ou discriminar qualquer Profissional, membro da nossa equipe ou qualquer outra pessoa;' },
      { kind: 'li', text: '(e) enviar ou transmitir qualquer coisa ilegal, difamatória ou que viole direitos de alguém;' },
      { kind: 'li', text: '(f) tentar obter acesso não autorizado ao Serviço, interrompê-lo ou introduzir código malicioso;' },
      { kind: 'li', text: '(g) usar meios automatizados para acessar, extrair ou interagir com o Serviço sem a nossa permissão por escrito; ou' },
      { kind: 'li', text: '(h) revender, sublicenciar ou explorar comercialmente o Serviço ou qualquer Conteúdo.' },
      { kind: 'p', text: '8.2 Podemos investigar suspeitas de violação e tomar medidas proporcionais, que podem incluir advertência, restrição de um recurso, suspensão ou encerramento. Quando tomarmos uma medida, diremos a você o motivo, salvo se a lei nos impedir.' },
      { kind: 'h', text: '9. Denúncia de conteúdo e a nossa resposta' },
      { kind: 'p', text: '9.1 Se você encontrar no Serviço conteúdo ilegal, prejudicial ou contrário a estes Termos, denuncie em [email] ou pela função de denúncia. Diga qual é o conteúdo, onde está e por que está denunciando.' },
      { kind: 'p', text: '9.2 Avaliaremos toda denúncia que recebermos. Quando for fundamentada, removeremos ou restringiremos o acesso ao conteúdo e tomaremos qualquer outra medida apropriada. Comunicaremos o resultado a você e, se um conteúdo seu for removido, diremos por quê e como contestar essa decisão.' },
      { kind: 'p', text: '9.3 Mantemos registro das denúncias e do que fizemos a respeito.' },
      { kind: 'h', text: '10. Serviços guiados por profissional' },
      { kind: 'p', text: '10.1 Quando você agenda um Profissional pelo Good Loop, surge uma relação separada entre você e esse Profissional. O seu consentimento informado e quaisquer condições acordadas com o Profissional regem essa relação e, nas questões clínicas, prevalecem sobre estes Termos.' },
      { kind: 'p', text: '10.2 Verificamos no ingresso, e periodicamente depois, que cada Profissional mantém registro ativo no conselho profissional competente. Não garantimos a competência clínica de nenhum Profissional, a sua adequação a você ou qualquer resultado.' },
      { kind: 'p', text: '10.3 O Profissional decide se trabalhar com você a distância é adequado à sua situação, e pode recusar ou encaminhar você a outro lugar. Essa decisão é dele e não a influenciamos.' },
      { kind: 'p', text: '10.4 As sessões devem ser realizadas no horário agendado. As nossas regras de cancelamento e remarcação de sessões estão publicadas na plataforma e fazem parte destes Termos; aplicam-se igualmente a você e ao Profissional.' },
      { kind: 'p', text: '10.5 Se um Profissional ficar indisponível, ajudaremos você a encontrar uma alternativa, quando houver. Quando uma relação terapêutica estiver em andamento, apoiaremos uma transição ordenada conforme a cláusula 15.4.' },
      { kind: 'h', text: '11. Preços, pagamento e assinaturas' },
      { kind: 'p', text: '11.1 Os preços são os exibidos no momento da compra, na moeda indicada, e incluem os tributos aplicáveis, salvo indicação em contrário.' },
      { kind: 'p', text: '11.2 Quando você compra uma assinatura, diremos claramente antes da compra: o que você recebe, o preço, o período de cobrança, que a assinatura se renova automaticamente, o preço na renovação e como interrompê-la. A sua aceitação da renovação automática é colhida separadamente da sua aceitação destes Termos.' },
      { kind: 'p', text: '11.3 A assinatura se renova automaticamente ao fim de cada período de cobrança pelo preço então informado a você, salvo se você cancelar antes da data de renovação. Lembraremos você antes de cada renovação quando a lei exigir e, em todo caso, antes de qualquer renovação de período superior a um mês.' },
      { kind: 'p', text: '11.4 Se alterarmos o preço da sua assinatura, avisaremos pelo menos [trinta] dias antes de a alteração entrar em vigor e você poderá cancelar antes disso. Uma alteração de preço nunca se aplica a um período que você já pagou.' },
      { kind: 'p', text: '11.5 Se um pagamento falhar, avisaremos você e poderemos suspender o acesso até a regularização. Não encerraremos o Serviço por um pagamento não realizado sem dar a você uma oportunidade razoável de corrigi-lo.' },
      { kind: 'p', text: '11.6 Os pagamentos são processados por [provedor de pagamento]. As condições dele regem o processamento do seu pagamento, e não armazenamos os dados completos do seu cartão.' },
      { kind: 'h', text: '12. Cancelamento e desistência' },
      { kind: 'p', text: '12.1 Você pode cancelar uma assinatura a qualquer momento, com efeito ao fim do período de cobrança em curso, pelas configurações da sua conta. Cancelar nunca deve ser mais difícil do que assinar; se você perceber que é, nos avise e cancelaremos por você.' },
      { kind: 'p', text: '12.2 Direito legal de desistência. Você tem o direito, previsto em lei, de desistir de um contrato a distância, além do direito de cancelamento da cláusula 12.1. O prazo e a forma variam por país e estão no anexo que se aplica a você:' },
      { kind: 'li', text: '(a) se você mora no Brasil, aplica-se o Anexo I e o prazo é de sete dias; e' },
      { kind: 'li', text: '(b) se você mora em um Estado-membro da União Europeia, aplica-se o Anexo II e o prazo é de quatorze dias.' },
      { kind: 'p', text: 'Nos termos do artigo 49 do Código de Defesa do Consumidor, por ter contratado fora do nosso estabelecimento comercial, você pode desistir deste contrato no prazo de sete dias a contar da data da contratação ou da data em que acessou o Serviço pela primeira vez, o que for posterior, sem precisar dar motivo.', market: 'BR' },
      { kind: 'p', text: 'Para desistir, avise-nos em [email] ou pela plataforma. Devolveremos todos os valores pagos, monetariamente atualizados, de imediato, pelo mesmo meio de pagamento que você usou. Você não precisa dar motivo e não cobraremos nada pela desistência.', market: 'BR' },
      { kind: 'p', text: 'Você tem quatorze dias a contar do dia da celebração do contrato para desistir dele, sem precisar dar motivo.', market: 'EU' },
      { kind: 'p', text: 'Para desistir, avise-nos por declaração inequívoca — um e-mail para [email] é suficiente — ou use o formulário-modelo de desistência disponível na nossa página de informações legais. Basta enviar a comunicação antes do fim dos quatorze dias.', market: 'EU' },
      { kind: 'p', text: 'Devolveremos todos os pagamentos recebidos de você em até quatorze dias após sermos informados, pelo mesmo meio de pagamento que você usou, sem custo para você.', market: 'EU' },
      { kind: 'p', text: 'Se você nos pediu para começar a prestar o Serviço durante o prazo de desistência e depois desistiu, você paga apenas um valor proporcional ao que foi prestado até o momento em que nos avisou.', market: 'EU' },
      { kind: 'p', text: '12.3 Para desistir, avise-nos dentro do prazo aplicável por qualquer declaração clara — um e-mail basta — ou pelo formulário fornecido no anexo pertinente. Devolveremos o que for devido no prazo indicado nesse anexo, pelo mesmo meio de pagamento que você usou.' },
      { kind: 'p', text: '12.4 Fora do prazo legal, aplica-se a nossa política de reembolso publicada na plataforma. Essa política não reduz, e não pode reduzir, os seus direitos legais.' },
      { kind: 'h', text: '13. Alterações no Serviço' },
      { kind: 'p', text: '13.1 Melhoramos o Serviço continuamente e podemos adicionar, alterar ou remover recursos. Não faremos uma alteração que reduza substancialmente aquilo pelo qual você pagou durante um período já pago.' },
      { kind: 'p', text: '13.2 Se fizermos uma alteração que afete você de forma substancial e adversa, avisaremos com antecedência e você poderá rescindir e receber o reembolso proporcional de qualquer valor pago pelo período não usado.' },
      { kind: 'h', text: '14. Disponibilidade' },
      { kind: 'p', text: '14.1 Trabalhamos para manter o Serviço disponível, mas ele pode ser interrompido por manutenção, por razões técnicas ou por eventos fora do nosso controle. Avisaremos sobre manutenção programada quando razoavelmente possível.' },
      { kind: 'p', text: '14.2 O Serviço depende do seu dispositivo, do seu software e da sua conexão com a internet, que são responsabilidade sua.' },
      { kind: 'h', text: '15. Suspensão, encerramento e continuidade' },
      { kind: 'p', text: '15.1 Você pode encerrar a sua conta a qualquer momento.' },
      { kind: 'p', text: '15.2 Podemos suspender ou encerrar o seu acesso se você violar substancialmente estes Termos, se a lei nos obrigar, ou se continuar a prestar o Serviço expuser você ou outra pessoa a um risco grave. Salvo se a violação for grave ou a lei exigir ação imediata, daremos aviso prévio e oportunidade de corrigir.' },
      { kind: 'p', text: '15.3 No encerramento, o seu direito de usar o Serviço termina. Trataremos os seus dados pessoais conforme o nosso Aviso de Privacidade e manteremos apenas o que a lei nos obrigar a manter.' },
      { kind: 'p', text: '15.4 Continuidade do cuidado. Quando uma relação terapêutica com um Profissional estiver em andamento e o seu acesso estiver prestes a terminar por qualquer motivo, avisaremos com antecedência, informaremos o Profissional para que ele possa cumprir as suas próprias obrigações com você, e apoiaremos uma conclusão ou transição ordenada. Não encerraremos abruptamente uma relação terapêutica quando estiver ao nosso alcance evitar isso.' },
      { kind: 'p', text: '15.5 As cláusulas 7, 16, 17, 20, 23 e qualquer outra que por sua natureza deva continuar sobrevivem ao encerramento.' },
      { kind: 'h', text: '16. A nossa responsabilidade com você' },
      { kind: 'p', text: 'Somos responsáveis por prestar o Serviço com a qualidade, a segurança e a adequação que você pode legitimamente esperar, de acordo com o Código de Defesa do Consumidor. Não excluímos, reduzimos nem transferimos essa responsabilidade, e nada nestes Termos deve ser lido como tentativa de fazê-lo.', market: 'BR' },
      { kind: 'p', text: 'O que nos comprometemos a fornecer está descrito na cláusula 6 e nos Avisos da plataforma. No uso por conta própria, fornecemos um serviço de bem-estar; não fornecemos tratamento, diagnóstico ou cuidado clínico, e não afirmamos fazê-lo. Quando um Profissional guia o seu uso do Good Loop, esse Profissional presta o serviço psicológico e é responsável pelos seus próprios atos clínicos, conforme D-05 e D-07, enquanto permanecemos responsáveis pelo funcionamento e pela segurança da plataforma conforme descrito e pela verificação do registro do Profissional conforme a cláusula 10.2.', market: 'BR' },
      { kind: 'p', text: 'Se o Serviço apresentar vício, você tem os direitos que o Código de Defesa do Consumidor lhe dá, incluindo o reparo do vício, a substituição do serviço, o abatimento proporcional do preço ou a restituição do valor pago, monetariamente atualizado, além da indenização por eventuais perdas. Avise-nos em [email] e cuidaremos disso.', market: 'BR' },
      { kind: 'p', text: '16.1 Prestaremos o Serviço com cuidado e competência razoáveis.', market: 'EU' },
      { kind: 'p', text: '16.2 Somos responsáveis pelas perdas que você sofrer como resultado previsível de uma violação destes Termos por nós ou da nossa falta de cuidado e competência razoáveis. Não somos responsáveis por perdas imprevisíveis.', market: 'EU' },
      { kind: 'p', text: '16.3 Não excluímos nem limitamos a nossa responsabilidade de nenhuma forma onde fazê-lo seria ilegal. Isso inclui a responsabilidade por morte ou lesão pessoal causada por nossa negligência, por fraude ou declaração fraudulenta, por qualquer violação dos seus direitos legais como consumidor e por qualquer responsabilidade que não possa ser excluída pela lei de proteção de dados que se aplica a você.', market: 'EU' },
      { kind: 'p', text: '16.4 Sujeito à cláusula 16.3, a nossa responsabilidade total com você em relação ao Serviço em qualquer período de doze meses é limitada ao maior valor entre o que você nos pagou nesse período e [EUR 500].', market: 'EU' },
      { kind: 'p', text: '16.5 Não somos responsáveis pelo conteúdo clínico, pela qualidade ou pelo resultado do que um Profissional decide no seu caso, que é responsabilidade do próprio Profissional, conforme D-05 e D-07. Isso não afeta a nossa responsabilidade pela verificação do registro conforme a cláusula 10.2, nem pelo funcionamento e pela segurança do Serviço.', market: 'EU' },
      { kind: 'p', text: '16.6 Não somos responsáveis por sites, aplicativos ou serviços de terceiros, conforme D-14.', market: 'EU' },
      { kind: 'p', text: '16.7 Fornecemos o Serviço para uso pessoal. Não temos responsabilidade com você por lucros cessantes, perda de negócios, interrupção de atividades ou perda de oportunidades comerciais.', market: 'EU' },
      { kind: 'h', text: '17. A sua responsabilidade conosco' },
      { kind: 'p', text: '17.1 Se você usar o Serviço de forma ilegal, ou em grave violação da cláusula 8, e sofrermos perdas em consequência, você é responsável por essas perdas na medida permitida pela lei.' },
      { kind: 'h', text: '18. Os seus dados pessoais' },
      { kind: 'p', text: '18.1 Tratamos os seus dados pessoais conforme o nosso Aviso de Privacidade, que faz parte destes Termos.' },
      { kind: 'p', text: '18.2 As informações sobre a sua saúde mental são sensíveis e são tratadas como tais. Quando um Profissional trabalha com você, o registro clínico é mantido por esse Profissional sob as suas próprias obrigações profissionais, e não o usamos para os nossos fins.' },
      { kind: 'p', text: '18.3 Você tem direitos sobre os seus dados pessoais, incluindo os direitos de acesso, correção, exclusão, portabilidade e oposição. O Aviso de Privacidade explica como exercê-los e como contatar o nosso encarregado pela proteção de dados e, se desejar, a autoridade de controle.' },
      { kind: 'h', text: '19. Se algo der errado' },
      { kind: 'p', text: '19.1 Fale conosco primeiro. Escreva para [email]: confirmaremos o recebimento em até [dois] dias úteis e responderemos ao mérito em até [dez] dias úteis, dizendo o que apuramos e o que propomos fazer.' },
      { kind: 'p', text: '19.2 Se você não ficar satisfeito, pode levar o assunto adiante. Nada nestes Termos exige que você use o nosso processo de reclamação antes de exercer qualquer direito, e nada exige que você recorra à arbitragem.' },
      { kind: 'p', text: '19.3 Quando uma reclamação disser respeito à conduta de um Profissional, você também pode reclamar ao conselho profissional dele. Forneceremos os contatos mediante solicitação.' },
      { kind: 'p', text: '19.4 O anexo que se aplica a você indica os órgãos de defesa do consumidor e as vias de resolução de conflitos disponíveis no seu país.' },
      { kind: 'h', text: '20. Lei aplicável e foro' },
      { kind: 'p', text: 'Estes Termos são regidos pela lei brasileira, em especial pelo Código de Defesa do Consumidor (Lei 8.078/1990), pela Lei Geral de Proteção de Dados (Lei 13.709/2018) e pelo Marco Civil da Internet (Lei 12.965/2014).', market: 'BR' },
      { kind: 'p', text: 'Você pode propor qualquer ação no foro do seu próprio domicílio, e nada nestes Termos restringe isso.', market: 'BR' },
      { kind: 'p', text: 'Estes Termos não contêm cláusula de arbitragem. Você não é obrigado a arbitrar nenhuma disputa conosco, e nada nestes Termos renuncia ao seu direito de participar de uma ação coletiva.', market: 'BR' },
      { kind: 'p', text: 'Antes de ir ao Judiciário você pode, se quiser, usar o nosso canal de reclamação, contatar o PROCON do seu estado ou usar a plataforma federal consumidor.gov.br. São opções disponíveis a você, não condições a cumprir.', market: 'BR' },
      { kind: 'p', text: 'Estes Termos são regidos pela lei do Estado-membro em que você reside habitualmente.', market: 'EU' },
      { kind: 'p', text: 'Você pode propor ações nos tribunais desse Estado-membro, e só proporemos ações contra você lá.', market: 'EU' },
      { kind: 'p', text: 'Você também pode usar a plataforma europeia de resolução de litígios online ou qualquer órgão de resolução alternativa de conflitos aplicável no seu país. Os detalhes estão na nossa página de informações legais. Usá-los é opcional.', market: 'EU' },
      { kind: 'h', text: '21. Alterações nestes Termos' },
      { kind: 'p', text: '21.1 Podemos alterar estes Termos. Avisaremos pelo menos [trinta] dias antes de uma alteração que afete você de forma substancial entrar em vigor, por e-mail e na plataforma, e publicaremos o que mudou.' },
      { kind: 'p', text: '21.2 Se você não aceitar uma alteração, pode rescindir antes de ela entrar em vigor e receber o reembolso proporcional de qualquer valor pago pelo período não usado. Continuar a usar o Serviço depois que a alteração entra em vigor significa aceitá-la.' },
      { kind: 'p', text: '21.3 Mantemos as versões anteriores destes Termos disponíveis na nossa página de informações legais, com a data em que cada uma esteve em vigor.' },
      { kind: 'p', text: '21.4 Não alteraremos estes Termos retroativamente, e não os alteraremos unilateralmente de forma que reduza aquilo pelo qual você já pagou.' },
      { kind: 'h', text: '22. Transferência deste contrato' },
      { kind: 'p', text: '22.1 Podemos transferir os nossos direitos e obrigações sob estes Termos a outra organização, por exemplo em uma reorganização ou venda do negócio. Avisaremos você se o fizermos, e a transferência não reduzirá os seus direitos. Se você não quiser continuar, pode rescindir e receber o reembolso proporcional de qualquer valor pago pelo período não usado.' },
      { kind: 'p', text: '22.2 Você não pode transferir os seus direitos ou obrigações a outra pessoa.' },
      { kind: 'h', text: '23. Disposições gerais' },
      { kind: 'p', text: '23.1 Independência das cláusulas. Se qualquer disposição destes Termos for considerada inválida ou inexequível, as demais continuam em vigor, e a disposição inválida é substituída por uma válida que mais se aproxime da sua finalidade.' },
      { kind: 'p', text: '23.2 Não renúncia. Se não exercermos um direito imediatamente, não o perdemos.' },
      { kind: 'p', text: '23.3 Acordo integral. Estes Termos, junto com os documentos que incorporam, constituem o acordo integral entre nós sobre o Serviço. Isso não exclui a responsabilidade por algo que tenhamos dito de forma desonesta, nem afeta declarações que nos vinculem pela lei do consumidor.' },
      { kind: 'p', text: '23.4 Idioma. Estes Termos são publicados em [português / italiano / inglês]. A versão em [português] rege para os usuários no Brasil e a versão em [italiano] rege para os usuários na Itália. As demais versões são fornecidas por conveniência.' },
      { kind: 'p', text: '23.5 Eventos fora do nosso controle. Não somos responsáveis por não cumprir quando a causa está fora do nosso controle razoável, mas avisaremos você e não cobraremos por um serviço que não podemos prestar.' },
      { kind: 'p', text: '23.6 Versão. Esta é a versão [1.0], em vigor a partir de [data].' },
    ],
  },
  supplement: {
    id: 'supplement',
    title: 'Suplemento do usuário final — acesso patrocinado',
    blocks: [
      { kind: 'h', text: 'S1. Por que você está lendo isto' },
      { kind: 'p', text: 'O seu acesso ao Good Loop está sendo pago pelo seu empregador ou por outra organização (o seu «Patrocinador»). Este Suplemento explica o que isso significa. Ele se soma aos Termos e condições e, onde os dois divergirem em algo relativo ao seu Patrocinador, aplica-se este Suplemento.' },
      { kind: 'h', text: 'S2. O seu Patrocinador não é parte do seu uso do Good Loop' },
      { kind: 'p', text: 'O seu Patrocinador tem um acordo comercial conosco. Ele não é parte do acordo entre você e nós, e não tem nenhum direito sobre a sua conta, as suas informações ou o seu cuidado.' },
      { kind: 'h', text: 'S3. O que o seu Patrocinador nunca recebe' },
      { kind: 'p', text: 'O Aviso sobre confidencialidade perante empregador e patrocinador (D-08) faz parte deste Suplemento e é um compromisso vinculante que assumimos com você. Em resumo: o seu Patrocinador nunca receberá se, quando ou com que frequência você usou o Good Loop, o que você fez, qualquer coisa que escreveu, se agendou ou compareceu a uma sessão, quem você viu, o que foi discutido, ou qualquer coisa a partir da qual algo disso possa razoavelmente ser deduzido.' },
      { kind: 'h', text: 'S4. O que o seu Patrocinador recebe' },
      { kind: 'p', text: 'Informações agregadas e desidentificadas sobre o programa como um todo, nunca derivadas de um grupo com menos de [vinte e cinco] pessoas. Os números abaixo desse limite são suprimidos, não informados.' },
      { kind: 'h', text: 'S5. O seu Patrocinador não pode pedir que você abra mão dessa proteção' },
      { kind: 'p', text: 'O nosso acordo com o seu Patrocinador exige que ele não busque informações individuais sobre você, não peça que você revele o seu uso do Good Loop e não trate você de forma diferente por ter usado ou por não ter usado. Se você acredita que o seu Patrocinador fez qualquer dessas coisas, avise-nos em [email]. Você também pode levar o caso à autoridade de proteção de dados do seu país.' },
      { kind: 'h', text: 'S6. Se o patrocínio terminar' },
      { kind: 'p', text: 'Se o seu Patrocinador deixar de pagar, ou se você sair da organização, daremos pelo menos [trinta] dias de aviso antes que o seu acesso mude. Diremos o que acontece com as suas informações e, onde houver opção de continuação, explicaremos como ativá-la. Se você estiver trabalhando com um Profissional nesse momento, aplica-se a cláusula 15.4 dos Termos e apoiaremos uma conclusão ou transição ordenada.' },
      { kind: 'h', text: 'S7. Usar o Good Loop é uma escolha sua' },
      { kind: 'p', text: 'O seu Patrocinador pode disponibilizar o Good Loop a você, mas não pode obrigar você a usá-lo, e escolher não usar não é assunto do seu Patrocinador.' },
    ],
  },
  professional: {
    id: 'professional',
    title: 'Termos para profissionais',
    blocks: [
      { kind: 'h', text: 'P1. Condição e independência' },
      { kind: 'p', text: 'P1.1 O Profissional é um prestador independente, não um empregado do Good Loop, e exerce julgamento profissional independente. Não se cria nenhuma relação de agência ou sociedade.' },
      { kind: 'p', text: 'P1.2 O Good Loop não dirige decisões clínicas. Qualquer sugestão gerada pela plataforma, inclusive por um recurso automatizado, é meramente orientativa e pode ser desconsiderada.' },
      { kind: 'h', text: 'P2. Registro e competência' },
      { kind: 'p', text: 'P2.1 O Profissional garante que mantém registro ativo no conselho profissional competente, que está autorizado a exercer no território de onde exerce e em relação às pessoas que atende, que não há processo disciplinar pendente contra ele, e que notificará o Good Loop imediatamente se algo disso mudar.' },
      { kind: 'p', text: 'P2.2 O Profissional é responsável por avaliar se a prestação a distância, e a aplicação da Metodologia GL, são adequadas a cada pessoa, e por recusar ou encaminhar quando não são — em conformidade com a Resolução CFP 9/2024 no Brasil e com as orientações do CNOP na Itália.' },
      { kind: 'p', text: 'P2.3 O Profissional deve cumprir os requisitos territoriais das suas normas profissionais, inclusive qualquer exigência de exercer a partir de determinado território ou de uma conexão nele registrada.' },
      { kind: 'p', text: 'P2.4 O Good Loop verifica o registro no ingresso e periodicamente depois, e pode suspender um Profissional enquanto a verificação estiver pendente.' },
      { kind: 'h', text: 'P3. Responsabilidade clínica e registros' },
      { kind: 'p', text: 'P3.1 O Profissional detém a relação clínica e carrega a responsabilidade clínica e profissional por ela.' },
      { kind: 'p', text: 'P3.2 O Profissional é responsável por obter consentimento informado que cubra, no mínimo: a natureza e a finalidade da intervenção; que ela é prestada a distância e o que isso significa; os limites do meio e o que acontece se a conexão cair; a confidencialidade e os seus limites; como os registros são mantidos, onde, por quanto tempo e quem pode acessá-los; as providências caso a pessoa esteja em risco; honorários e cancelamento; e as alternativas ao trabalho a distância. O Profissional deve documentar esse consentimento.' },
      { kind: 'p', text: 'P3.3 O Profissional mantém o registro profissional exigido pelo seu conselho e é o controlador dele. O Good Loop não o usa para os seus próprios fins.' },
      { kind: 'p', text: 'P3.4 O Profissional deve seguir o procedimento de escalonamento publicado pelo Good Loop quando uma pessoa revela um risco, sem prejuízo do seu próprio julgamento e dos seus deveres profissionais, que prevalecem.' },
      { kind: 'p', text: 'P3.5 Quando uma relação terapêutica precisar terminar, o Profissional deve concluí-la ou transferi-la de acordo com as suas obrigações profissionais, e não deve interrompê-la abruptamente.' },
      { kind: 'h', text: 'P4. Metodologia, confidencialidade e propriedade intelectual' },
      { kind: 'p', text: 'P4.1 O Profissional recebe uma licença limitada, revogável e não exclusiva para usar a biblioteca de conteúdo do Good Loop exclusivamente no cuidado que ele próprio presta pelo Good Loop, e para nenhum outro fim. O Profissional seleciona qual conteúdo usar e quando; o Good Loop não prescreve sequência nem apresenta a biblioteca como protocolo ou curso de tratamento.' },
      { kind: 'p', text: 'P4.2 O Profissional não deve divulgar, reproduzir, ensinar, publicar ou explorar comercialmente a Metodologia GL; não deve usá-la fora do Good Loop; não deve usá-la, nem qualquer resultado da plataforma, para desenvolver, treinar ou avaliar qualquer produto, modelo ou serviço concorrente; e deve devolver ou destruir todos os materiais no término. Essas obrigações sobrevivem ao término por prazo indeterminado quanto aos elementos confidenciais.' },
      { kind: 'p', text: 'P4.3 O Profissional não deve gravar sessões, exceto com o consentimento separado e documentado da pessoa, onde as normas profissionais permitirem, e não deve compartilhar nenhuma gravação.' },
      { kind: 'p', text: 'P4.4 O Profissional deve manter confidenciais todas as informações sobre as pessoas atendidas e sobre o negócio do Good Loop.' },
      { kind: 'p', text: 'P4.5 O Profissional reconhece que é o único responsável pelo cuidado, que o julgamento clínico sobre se e como usar o conteúdo é dele, e que não descreverá o Good Loop a nenhuma pessoa atendida como prestador de tratamento ou como executor de um protocolo terapêutico.' },
      { kind: 'h', text: 'P5. Seguro, indenização e término' },
      { kind: 'p', text: 'P5.1 O Profissional deve manter seguro de responsabilidade profissional de valor não inferior a [valor] e apresentar comprovação mediante solicitação.' },
      { kind: 'p', text: 'P5.2 O Profissional indeniza o Good Loop por reclamações decorrentes dos seus atos e omissões clínicos, da violação destes termos e da violação das suas obrigações profissionais.' },
      { kind: 'p', text: 'P5.3 O Good Loop pode suspender ou encerrar o vínculo imediatamente se o registro caducar, se for instaurado processo disciplinar ou se houver risco grave a uma pessoa atendida — sujeito, em todo caso, à obrigação de continuidade do item P3.5.' },
    ],
  },
}
