/* ============================================================================
   Good Loop — legal texts, ITALIAN — PRIMA BOZZA

   Block-for-block rendering of legal-en.ts (the working master) in Italian.
   Part VI.4 of the Terms deliverable: the Italian version is the GOVERNING
   one in Italy and must be prepared through counsel qualified there. This
   draft exists so that no person meets an English legal sentence in an
   Italian interface and so that counsel has a concrete text to correct; it
   is not that review. The version string in types.ts says "draft" for the
   same reason. Clauses 16 and 20 are not translations of the English clause
   but the Annex II text, as Part VI.4 requires.

   Register: "tu", as the rest of the Self Use surface. "Sessione", never
   "seduta"; "benessere", never "salute mentale" outside referral language
   (Lexicon_Notes 2, 13, 14).
   ============================================================================ */

import type { LegalDocText } from './types'

export const LEGAL_IT: Record<string, LegalDocText> = {
  'D-01': {
    id: 'D-01',
    title: 'Importante — leggi prima di usare Good Loop',
    blocks: [
      { kind: 'p', text: 'Good Loop è una piattaforma digitale per il benessere psicologico. È offerta in due modi distinti, e i tuoi diritti e le nostre responsabilità cambiano a seconda di quale si applica a te.' },
      { kind: 'p', text: 'Quando usi Good Loop da solo, senza un professionista che ti guida, Good Loop è un servizio di benessere. È pensato per il rilassamento, la riflessione personale e per imparare qualcosa sul benessere psicologico. Non è un trattamento, non è una terapia e non valuta, diagnostica né gestisce alcuna condizione di salute.' },
      { kind: 'p', text: 'Quando un professionista abilitato usa Good Loop per guidarti, è quel professionista — e non Good Loop — a fornirti il servizio psicologico. Il professionista è responsabile delle decisioni cliniche prese, dell’adeguatezza dell’approccio alla tua situazione e dei propri obblighi professionali ed etici. Good Loop fornisce la tecnologia, la metodologia e l’ambiente in cui quel servizio viene erogato.' },
      { kind: 'p', text: 'Good Loop non è un servizio di emergenza e non deve mai essere usato in un’emergenza. Se sei a rischio, o pensi che qualcun altro lo sia, fermati e cerca aiuto immediato — vedi l’Informativa su crisi ed emergenze.' },
      { kind: 'p', text: 'Le seguenti informative fanno parte di questi Termini e si applicano al tuo uso di Good Loop: l’Informativa sulla natura del servizio; l’Informativa su crisi ed emergenze; l’Informativa sull’uso autonomo; l’Informativa sull’uso guidato da un professionista; l’Informativa sulle funzioni automatizzate; l’Informativa su riservatezza e dati; e le altre informative pubblicate nella nostra pagina di informazioni legali. Ti chiediamo di leggerle. In caso di contrasto tra il riassunto di un’informativa e il suo testo integrale, vale il testo integrale.' },
      { kind: 'p', text: 'Se non sei d’accordo con queste informative, ti chiediamo di non usare Good Loop.' },
    ],
  },
  'D-02': {
    id: 'D-02',
    title: 'Natura del servizio e destinazione d’uso',
    blocks: [
      { kind: 'h', text: 'Destinazione d’uso' },
      { kind: 'p', text: 'Il software di Good Loop fornisce contenuti audio preregistrati e strumenti per organizzare le sessioni a persone adulte di almeno diciotto anni, in due modi: (i) come risorsa di benessere a uso autonomo, con contenuti di rilassamento, riflessione personale e psicoeducazione; e (ii) come libreria di contenuti e strumenti da cui un professionista abilitato sceglie in modo indipendente, e che quel professionista può usare all’interno di una cura che progetta, eroga e di cui resta clinicamente responsabile.' },
      { kind: 'h', text: 'Che cosa Good Loop non è' },
      { kind: 'p', text: 'Good Loop non è un dispositivo medico. Non diagnostica, non tratta, non cura, non previene, non monitora e non predice alcuna malattia, disturbo o condizione clinica. Non stabilisce, né pretende di stabilire, se hai una condizione, quanto sia grave o quali cure dovresti ricevere. Non seleziona, non sequenzia, non consiglia e non adatta contenuti sulla base di qualcosa che ti riguarda. Good Loop non prescrive e non dà alcuna indicazione sui farmaci; se qualcosa nella piattaforma dovesse mai sembrare farlo, ignoralo e diccelo.' },
      { kind: 'p', text: 'Good Loop non sostituisce il parere, la diagnosi o il trattamento di un medico, di uno psichiatra o di uno psicologo. Per qualsiasi domanda sulla tua salute o sulla tua salute mentale rivolgiti sempre a un professionista sanitario qualificato. Non ignorare mai un parere professionale, e non rimandare mai il momento di chiederlo, per qualcosa che hai letto, visto o fatto su Good Loop. Non iniziare, interrompere o modificare mai un farmaco a causa di Good Loop.' },
      { kind: 'p', text: 'Good Loop non è adatto, e non è offerto, per una crisi di salute mentale, un’emergenza o una situazione di rischio per te o per qualsiasi altra persona. Good Loop non è adatto a persone con una malattia mentale grave o persistente che richiede cure specialistiche, e non è progettato per l’uso dove serve una valutazione clinica di persona.' },
      { kind: 'p', text: 'Good Loop non va usato per ottenere alcuna determinazione, certificazione, relazione o documentazione ufficiale — anche a fini giudiziari, lavorativi, assicurativi, migratori o previdenziali — e nessun risultato della piattaforma va presentato o considerato a tale scopo.' },
      { kind: 'h', text: 'Come sono organizzati i nostri contenuti' },
      { kind: 'p', text: 'Le nostre sessioni sono raggruppate per la situazione in cui potresti trovarti — una giornata di lavoro, un viaggio, la fine di una serata — così che tu possa trovarne una adatta al momento. Questo raggruppamento descrive una circostanza e nient’altro. Non è un’indicazione, non è un’affermazione su alcuna condizione, e nessuna sessione ti viene proposta sulla base di qualcosa che sappiamo o supponiamo sulla tua salute.' },
      { kind: 'h', text: 'A chi si rivolge' },
      { kind: 'p', text: 'Good Loop è offerto a persone adulte di almeno diciotto anni, nei territori in cui dichiariamo che è disponibile. Non è offerto a bambini o adolescenti.' },
    ],
  },
  'D-03-BR': {
    id: 'D-03-BR',
    title: 'Se sei a rischio, non usare Good Loop — chiedi aiuto adesso',
    blocks: [
      { kind: 'p', text: 'Good Loop non è un servizio di emergenza, non è monitorato in tempo reale e non può aiutarti in una crisi.' },
      { kind: 'p', text: 'Se stai pensando di toglierti la vita, di fare del male a te stesso o a un’altra persona, o se credi che tu o chiunque altro sia in pericolo, smetti di usare Good Loop e chiedi aiuto subito:' },
      { kind: 'p', text: 'Sostegno emotivo e prevenzione del suicidio — CVV: chiama il 188 (gratuito, 24 ore) o visita cvv.org.br' },
      { kind: 'p', text: 'Emergenza medica — SAMU: chiama il 192. Polizia ed emergenza generale: chiama il 190.' },
      { kind: 'p', text: 'Oppure vai al pronto soccorso dell’ospedale più vicino, o a una UPA o a un CAPS vicino a te.' },
      { kind: 'p', text: 'Se sei con una persona a rischio, non lasciarla sola e chiama aiuto.' },
      { kind: 'p', text: 'Nulla su Good Loop — compreso qualsiasi messaggio che invii all’interno della piattaforma, a un professionista o a qualsiasi funzione automatizzata — sarà trattato come una richiesta di soccorso, e nessun messaggio di questo tipo produrrà una risposta di emergenza. I messaggi inviati a un professionista non vengono letti in tempo reale e potrebbero non essere visti fino al suo successivo periodo di lavoro.' },
    ],
  },
  'D-03-EU': {
    id: 'D-03-EU',
    title: 'Se sei a rischio, non usare Good Loop — chiedi aiuto adesso',
    blocks: [
      { kind: 'p', text: 'Good Loop non è un servizio di emergenza, non è monitorato in tempo reale e non può aiutarti in una crisi.' },
      { kind: 'p', text: 'Se stai pensando di toglierti la vita, di fare del male a te stesso o a un’altra persona, o se credi che tu o chiunque altro sia in pericolo, smetti di usare Good Loop e chiedi aiuto subito:' },
      { kind: 'p', text: 'Servizi di emergenza — chiama il 112, il numero unico europeo di emergenza, gratuito da qualsiasi telefono.' },
      { kind: 'p', text: 'Oppure vai al pronto soccorso dell’ospedale più vicino.' },
      { kind: 'p', text: '[Inserire qui la linea nazionale verificata di ascolto e sostegno emotivo per ciascun Paese in cui il servizio è offerto, con nome, numero, orari e sito web.]' },
      { kind: 'p', text: 'Se sei con una persona a rischio, non lasciarla sola e chiama aiuto.' },
      { kind: 'p', text: 'Nulla su Good Loop — compreso qualsiasi messaggio che invii all’interno della piattaforma, a un professionista o a qualsiasi funzione automatizzata — sarà trattato come una richiesta di soccorso, e nessun messaggio di questo tipo produrrà una risposta di emergenza.' },
    ],
  },
  'D-04': {
    id: 'D-04',
    title: 'Quando usi Good Loop da solo',
    blocks: [
      { kind: 'p', text: 'Stai usando Good Loop da solo ogni volta che accedi ai suoi contenuti, esercizi o strumenti senza che un professionista abilitato guidi il tuo uso. Molto di ciò che segue è buon senso, ma conta, e vogliamo essere chiari.' },
      { kind: 'h', text: 'A cosa serve l’uso autonomo' },
      { kind: 'p', text: 'Rilassarsi. Riposare. Notare come ti senti e rifletterci. Imparare qualcosa sul benessere psicologico in termini generali. Costruire abitudini quotidiane che molte persone trovano utili. È tutto qui, e per molte persone è davvero utile.' },
      { kind: 'h', text: 'Che cosa l’uso autonomo non è' },
      { kind: 'p', text: 'Non è una terapia. Non è un trattamento. Non è un intervento clinico e non è un percorso di cura. Nulla di ciò che fai da solo dentro Good Loop è rivolto a una condizione che potresti avere, perché Good Loop non sa e non cerca di stabilire se ne hai una. Nessun esercizio, tecnica o contenuto che ti viene proposto nell’uso autonomo è stato scelto sulla base di una valutazione della tua salute.' },
      { kind: 'p', text: 'La Metodologia GL è una metodologia psicologica. Nell’uso autonomo ti vengono proposti contenuti generali di benessere che ne traggono spunto. Non stai ricevendo la Metodologia come trattamento, perché la Metodologia viene applicata come trattamento solo da un professionista qualificato che conosce la tua situazione e si assume la responsabilità di quell’applicazione.' },
      { kind: 'h', text: 'Perché le sessioni sono raggruppate per situazione' },
      { kind: 'p', text: 'Alcune sessioni sono fatte per un momento preciso — prima di un volo, tra una riunione e l’altra, a fine giornata. Perché il rilassamento funziona meglio quando si adatta alle circostanze in cui ti trovi davvero: quanto tempo hai, se puoi chiudere gli occhi, se sei seduto in uno spazio ristretto. Raggruppare le sessioni in questo modo riguarda il momento, non te. Non significa che pensiamo tu abbia una condizione, e scegliere una sessione non ci dice nulla sulla tua salute.' },
      { kind: 'h', text: 'Se ti serve di più' },
      { kind: 'p', text: 'Se stai facendo fatica, se qualcosa non migliora o se non sei sicuro che l’uso autonomo ti basti, parla con un professionista qualificato. Puoi organizzare un supporto guidato da un professionista attraverso Good Loop, dove è disponibile per te, oppure cercare aiuto per conto tuo. Ti chiediamo di non usare i contenuti a uso autonomo come motivo per rimandare un aiuto di cui potresti avere bisogno.' },
    ],
  },
  'D-05': {
    id: 'D-05',
    title: 'Quando un professionista guida il tuo uso di Good Loop',
    blocks: [
      { kind: 'p', text: 'Quando un professionista abilitato lavora con te attraverso Good Loop, il servizio psicologico ti viene fornito da quel professionista. Il professionista è indipendente. Good Loop fornisce contenuti audio e gli strumenti per organizzare le sessioni; il professionista decide che cosa usare, quando, e se sia adatto a te. Good Loop non fornisce il servizio psicologico, non partecipa alla tua cura e non consiglia, non sequenzia né adatta nulla per te.' },
      { kind: 'h', text: 'Di che cosa è responsabile il professionista' },
      { kind: 'p', text: 'Il professionista è responsabile di decidere se lavorare con te a distanza sia adeguato alla tua situazione; del giudizio clinico esercitato nel tuo caso; della selezione, dell’adattamento e dell’applicazione a te della Metodologia GL o di qualsiasi altro approccio; della tenuta della documentazione professionale richiesta dal suo ordine; del proprio segreto professionale; e del rispetto delle regole dell’ordine a cui è iscritto. Quelle decisioni sono sue, e Good Loop non le prende né le scavalca.' },
      { kind: 'h', text: 'Di che cosa è responsabile Good Loop' },
      { kind: 'p', text: 'Good Loop è responsabile del funzionamento della piattaforma come descritto, del fatto che i contenuti siano come li descriviamo, della verifica — all’ingresso e periodicamente in seguito — che ogni professionista abbia un’iscrizione in corso all’ordine professionale competente, e della sicurezza dell’ambiente. Good Loop non è responsabile del contenuto clinico, della qualità o dell’esito di ciò che un professionista decide nel tuo caso — compreso quali contenuti sceglie e come li usa.' },
      { kind: 'h', text: 'Che cosa non verifichiamo' },
      { kind: 'p', text: 'Verifichiamo l’iscrizione all’ordine. Non garantiamo la competenza clinica di alcun professionista, la sua adeguatezza per te o l’esito del lavoro con lui. Se un professionista non fa per te, diccelo e ti aiuteremo a cambiare; se ritieni che un professionista abbia agito in modo scorretto, diccelo e potrai anche rivolgerti al suo ordine professionale, di cui ti forniremo i contatti.' },
      { kind: 'h', text: 'Il tuo accordo con il professionista' },
      { kind: 'p', text: 'Il tuo rapporto con il professionista è regolato dal consenso informato e da eventuali condizioni di servizio concordate direttamente tra te e lui, in aggiunta a questi Termini. Dove quei documenti riguardano il rapporto clinico, prevalgono su questi Termini su quell’argomento.' },
    ],
  },
  'D-06': {
    id: 'D-06',
    title: 'Funzioni automatizzate e intelligenza artificiale',
    blocks: [
      { kind: 'p', text: 'Good Loop attualmente non usa l’intelligenza artificiale. Nessuna parte di Good Loop è generata, selezionata o valutata da un sistema di IA, e nessuna decisione che ti riguarda è presa con mezzi automatizzati.' },
      { kind: 'p', text: 'Non deduciamo le tue emozioni o intenzioni dal tuo volto, dalla tua voce o da qualsiasi altra caratteristica.' },
      { kind: 'p', text: 'Non usiamo i tuoi contenuti per addestrare modelli di intelligenza artificiale, e non permettiamo ad alcun nostro fornitore di farlo.' },
      { kind: 'p', text: 'Se introdurremo funzioni che usano l’intelligenza artificiale, te lo diremo in anticipo, le etichetteremo chiaramente ovunque compaiano e pubblicheremo una versione aggiornata di questa informativa prima che entrino in funzione.' },
    ],
  },
  'D-07': {
    id: 'D-07',
    title: 'Indipendenza professionale',
    blocks: [
      { kind: 'p', text: 'I professionisti che lavorano attraverso Good Loop esercitano un giudizio professionale indipendente. Good Loop non dirige, non istruisce, non riesamina, non scavalca né mette in discussione le decisioni cliniche di un professionista, e non richiede a un professionista di applicare la Metodologia GL, o una particolare tecnica al suo interno, ad alcuna persona.' },
      { kind: 'p', text: 'Il proprio ordine richiede al professionista di valutare se un dato approccio e un dato formato siano adeguati alla persona che ha davanti, e di rifiutare o inviare altrove quando non lo sono. Nulla nella piattaforma, nei materiali, nella formazione o negli accordi commerciali di Good Loop sostituisce quel dovere, e qualsiasi suggerimento, raccomandazione o indicazione generata dalla piattaforma è puramente indicativa e può essere ignorata dal professionista a sua discrezione.' },
      { kind: 'p', text: 'Good Loop non è il datore di lavoro dei professionisti che erogano servizi psicologici attraverso la piattaforma, salvo dove lo dichiariamo espressamente per iscritto, e questi Termini non creano alcun rapporto di agenzia, società o lavoro subordinato.' },
      { kind: 'p', text: 'Good Loop non consiglia contenuti, non suggerisce un ordine di utilizzo, non genera un piano e non varia ciò che è disponibile in base a qualcosa che riguarda una persona. La libreria è la stessa per ogni professionista. Selezione, ordine, tempi e interpretazione sono decisioni del solo professionista.' },
    ],
  },
  'D-08': {
    id: 'D-08',
    title: 'Che cosa il tuo datore di lavoro non vedrà mai',
    blocks: [
      { kind: 'p', text: 'Il tuo datore di lavoro, o qualunque organizzazione paghi il tuo accesso a Good Loop, ha acquistato un servizio per te. Non ha acquistato informazioni su di te. Questa informativa spiega esattamente che cosa quell’organizzazione può e non può sapere, ed è un impegno vincolante, non una dichiarazione di intenti.' },
      { kind: 'p', text: 'Il tuo sponsor non riceverà mai, e noi non gli comunicheremo mai:' },
      { kind: 'p', text: 'se hai usato Good Loop; quando o quanto spesso lo hai usato; quali contenuti hai visto o quali esercizi hai fatto; qualsiasi cosa tu abbia scritto, registrato o inserito; se hai prenotato, seguito o saltato una sessione; l’identità di qualsiasi professionista con cui hai lavorato; qualsiasi cosa discussa in una sessione; qualsiasi valutazione, nota, registrazione o osservazione su di te; o qualsiasi informazione da cui una di queste cose possa ragionevolmente essere dedotta.' },
      { kind: 'h', text: 'Che cosa riceve il tuo sponsor' },
      { kind: 'p', text: 'Il tuo sponsor riceve informazioni sul programma, non sulle persone: dati aggregati sull’adesione e sull’uso complessivi in tutta la sua popolazione, e una rendicontazione generale del servizio. Tutta questa rendicontazione è aggregata e priva di elementi identificativi, e non pubblichiamo alcun dato derivato da un gruppo inferiore a [venticinque] persone. Quando un gruppo è più piccolo di quella soglia, il dato viene nascosto anziché comunicato.' },
      { kind: 'h', text: 'Sessioni e informazioni cliniche' },
      { kind: 'p', text: 'Quando un professionista guida il tuo uso di Good Loop, ciò che passa tra te e quel professionista è coperto dal suo segreto professionale. Non è disponibile per il tuo sponsor in alcuna forma, in alcuna circostanza, e nessun contratto tra Good Loop e il tuo sponsor gli dà alcun diritto su di esso.' },
      { kind: 'h', text: 'Gli obblighi del tuo sponsor verso di te' },
      { kind: 'p', text: 'Il nostro accordo con il tuo sponsor gli impone di non chiederci informazioni individuali su di te, di non chiederti di rivelare il tuo uso di Good Loop e di non trattarti in modo diverso perché hai usato Good Loop o perché non lo hai fatto. Se ritieni che sia accaduto, diccelo usando i contatti indicati nei nostri Termini.' },
      { kind: 'h', text: 'Fine o modifica del tuo accesso sponsorizzato' },
      { kind: 'p', text: 'Se il tuo sponsor smette di pagare, o se lasci l’organizzazione, te lo diremo prima che il tuo accesso cambi e ti spiegheremo che cosa succede alle tue informazioni e come puoi continuare per conto tuo, dove questa opzione è disponibile.' },
    ],
  },
  'D-09': {
    id: 'D-09',
    title: 'Good Loop e i tuoi obblighi come datore di lavoro',
    blocks: [
      { kind: 'p', text: 'Good Loop è un servizio di benessere offerto alle tue persone. Non è un prodotto di conformità e non assolve alcun obbligo di legge che grava su di te.' },
      { kind: 'p', text: 'In particolare, e senza limitazione: fornire Good Loop non identifica, non valuta, non stima, non documenta e non gestisce i fattori di rischio psicosociale presenti nella tua organizzazione; non costituisce né contribuisce ad alcun inventario dei rischi, programma di gestione dei rischi, piano d’azione o valutazione dei rischi che sei tenuto a predisporre; non soddisfa alcun obbligo che tu possa avere in materia di salute e sicurezza sul lavoro, condizioni di lavoro o organizzazione del lavoro; e non è prova che un tale obbligo sia stato assolto.' },
      { kind: 'p', text: 'Obblighi di questo tipo riguardano le condizioni e l’organizzazione del lavoro nella tua azienda. Sono tuoi. Non vengono trasferiti a Good Loop da alcun accordo tra noi, e Good Loop non ne assume alcuno.' },
      { kind: 'p', text: 'Good Loop può far parte del supporto che scegli di offrire alle tue persone, e offrire un supporto di questo tipo può essere uno tra i molti elementi di come affronti il benessere sul lavoro. Se sia sufficiente, e che cos’altro tu debba fare, sono questioni che riguardano te e i tuoi consulenti.' },
      { kind: 'p', text: 'Good Loop non svolge valutazioni cliniche individuali dei tuoi dipendenti e non ti fornisce informazioni su alcun individuo. Nulla nel servizio è progettato o destinato a essere usato come meccanismo di valutazione del rischio psicosociale nella tua organizzazione.' },
    ],
  },
  'D-10': {
    id: 'D-10',
    title: 'Riservatezza, le tue informazioni e sicurezza',
    blocks: [
      { kind: 'h', text: 'Riservatezza' },
      { kind: 'p', text: 'Ciò che dici a un professionista attraverso Good Loop è riservato ed è protetto dal segreto professionale a cui quel professionista è tenuto secondo le regole della sua professione. Good Loop tratta le informazioni sul tuo uso della piattaforma come riservate e le comunica solo come descritto nella nostra Informativa sulla privacy.' },
      { kind: 'h', text: 'I limiti della riservatezza' },
      { kind: 'p', text: 'La riservatezza non è assoluta. Un professionista può essere tenuto dalla legge o dalle regole della sua professione a rivelare informazioni in circostanze ristrette — per esempio quando esiste un rischio grave e imminente per la tua vita o per quella di un’altra persona, quando un minore o una persona vulnerabile ha bisogno di protezione, o quando un tribunale o un’autorità competente ne richiede legittimamente la comunicazione. Il tuo professionista ti spiegherà questi limiti come parte del consenso informato e te lo dirà ogni volta che sia possibile e opportuno farlo.' },
      { kind: 'h', text: 'Registrazioni' },
      { kind: 'p', text: 'Non devi registrare, fotografare, catturare lo schermo o in altro modo acquisire alcuna sessione, e non devi condividere alcuna registrazione di questo tipo. I professionisti sono soggetti alla stessa regola e possono registrare solo con il tuo consenso separato, specifico e documentato, dove le loro regole professionali lo permettono.' },
      { kind: 'h', text: 'Sicurezza' },
      { kind: 'p', text: 'Prendiamo sul serio la sicurezza delle tue informazioni e applichiamo misure tecniche e organizzative adeguate alla loro sensibilità, tra cui la cifratura in transito e a riposo, controlli di accesso che limitano chi in Good Loop può vedere che cosa, la registrazione degli accessi e revisioni regolari. Lavoriamo solo con fornitori che rispettano gli standard che richiediamo.' },
      { kind: 'p', text: 'Nessun sistema connesso a internet può essere garantito come perfettamente sicuro, e non possiamo promettertelo. Ciò che promettiamo è che manterremo una protezione adeguata, che informeremo te e l’autorità competente se un incidente di sicurezza dovesse riguardare le tue informazioni in un modo che richiede una notifica, e che ti diremo che cosa è successo e che cosa stiamo facendo.' },
      { kind: 'h', text: 'La tua parte' },
      { kind: 'p', text: 'Ti chiediamo di tenere segrete le tue credenziali di accesso, di non condividere il tuo account e di usare Good Loop in un luogo riservato dove puoi parlare liberamente e dove nessuno può ascoltarti o vedere il tuo schermo. Avvisaci subito se pensi che qualcun altro abbia avuto accesso al tuo account.' },
    ],
  },
  'D-11': {
    id: 'D-11',
    title: 'Età',
    blocks: [
      { kind: 'p', text: 'Good Loop è offerto solo a persone di almeno diciotto anni. Non è progettato per bambini o adolescenti, non è offerto loro, non è adatto a loro e non viene pubblicizzato a loro.' },
      { kind: 'p', text: 'Usando Good Loop confermi di avere almeno diciotto anni e di avere la capacità giuridica di accettare questi Termini.' },
      { kind: 'p', text: 'Se veniamo a sapere che una persona minore di diciotto anni ha creato un account, sospenderemo l’account, cancelleremo i dati personali che conserviamo su quella persona salvo dove la legge ci impone di conservarli e, dove le circostanze lo richiedono, adotteremo le misure opportune per la sicurezza di quella persona.' },
    ],
  },
  'D-12': {
    id: 'D-12',
    title: 'Dove è offerto Good Loop',
    blocks: [
      { kind: 'p', text: 'Good Loop è offerto solo nei territori elencati sul nostro sito. Non offriamo Good Loop, e non lo rivolgiamo, a persone in altri territori.' },
      { kind: 'p', text: 'I servizi guidati da un professionista sono soggetti a una restrizione ulteriore. Un professionista può lavorare con te attraverso Good Loop solo se è iscritto e autorizzato a esercitare nel territorio che si applica alla tua situazione, e solo da un luogo da cui gli è permesso esercitare. Dove le regole professionali applicabili richiedono che un professionista sia fisicamente presente in un dato territorio, o operi da una connessione registrata in esso, il professionista deve rispettare quel requisito.' },
      { kind: 'p', text: 'Se ti trasferisci in un territorio in cui non offriamo il servizio, o accedi a Good Loop da lì, alcune o tutte le funzioni potrebbero non essere disponibili per te, e i servizi guidati da un professionista in particolare potrebbero essere sospesi finché la situazione non viene chiarita. È un vincolo legale, non una scelta commerciale.' },
      { kind: 'p', text: 'Sei responsabile del rispetto della legge del luogo da cui accedi a Good Loop.' },
    ],
  },
  'D-13': {
    id: 'D-13',
    title: 'Che cosa possiamo e non possiamo promettere',
    blocks: [
      { kind: 'p', text: 'Le persone rispondono in modo diverso al supporto per il benessere psicologico. Ciò che aiuta una persona può non aiutarne un’altra, e i progressi sono raramente lineari. Non promettiamo alcun risultato particolare dall’uso di Good Loop, e nessuno può farlo onestamente.' },
      { kind: 'p', text: 'Ci impegniamo a fornire il servizio con la cura, la competenza e la diligenza che ci si può ragionevolmente aspettare da un fornitore competente di un servizio di questo tipo, a descrivere accuratamente ciò che offriamo e a correggerlo quando sbagliamo. Non ci impegniamo ad alcun miglioramento specifico di come ti senti, ad alcun esito o ad alcuna tempistica, e nessuna dichiarazione fatta da noi, da un professionista o in uno dei nostri materiali va intesa come un impegno di questo tipo.' },
      { kind: 'p', text: 'Quando un professionista guida il tuo uso di Good Loop, anche l’obbligo del professionista è di diligente cura professionale e non una garanzia di alcun risultato clinico.' },
    ],
  },
  'D-14': {
    id: 'D-14',
    title: 'Contenuti e servizi che non controlliamo',
    blocks: [
      { kind: 'p', text: 'Good Loop può rimandare a, o collaborare con, siti web, applicazioni, risorse e servizi gestiti da altre organizzazioni — tra cui fornitori di pagamento, strumenti di comunicazione, organizzazioni di ascolto e di supporto, e contenuti prodotti da terzi. Non li controlliamo e non siamo responsabili di loro, dei loro contenuti, delle loro condizioni o di come gestiscono le tue informazioni.' },
      { kind: 'p', text: 'Un collegamento non è un’approvazione, salvo dove lo diciamo espressamente. Prima di usare un servizio di terzi, leggi le sue condizioni e la sua informativa sulla privacy.' },
      { kind: 'p', text: 'Good Loop può anche ospitare materiale fornito da utenti o da professionisti. Non esaminiamo tutto ciò che viene fornito prima che compaia. Se trovi su Good Loop contenuti illeciti, dannosi o contrari alle nostre regole, segnalaceli usando i contatti nei nostri Termini. Valuteremo ogni segnalazione che riceviamo e, quando una segnalazione è fondata, rimuoveremo o limiteremo l’accesso al contenuto e ti diremo che cosa abbiamo fatto.' },
    ],
  },
  'D-15': {
    id: 'D-15',
    title: 'Su ciò che diciamo, e che altri dicono, di Good Loop',
    blocks: [
      { kind: 'p', text: 'Descriviamo Good Loop come un servizio di benessere, perché è questo che è. Non affermiamo che Good Loop tratti, curi, prevenga o riduca i sintomi di alcuna malattia, disturbo o condizione, e qualsiasi dichiarazione che sembri affermarlo va ignorata e segnalata a noi.' },
      { kind: 'p', text: 'Quando pubblichiamo il racconto dell’esperienza di una persona, è l’esperienza di quella persona e nient’altro. Le esperienze individuali non sono tipiche, non sono prova di ciò che accadrà a chiunque altro e non sono una promessa di alcun risultato. Le testimonianze sono pubblicate con il consenso della persona interessata e possono essere accorciate; non sono retribuite, salvo dove lo diciamo.' },
      { kind: 'p', text: 'Quando citiamo una ricerca, indichiamo che cos’era la ricerca, che cosa ha misurato e quali sono i suoi limiti. Una ricerca su una metodologia, un approccio o una popolazione non è un’affermazione su di te.' },
      { kind: 'p', text: 'Descriviamo la nostra metodologia come capace di produrre un rilassamento più efficiente, e sessioni ben adattate a situazioni particolari. Sono affermazioni su come funziona la nostra metodologia, e ne conserviamo le prove. Non sono affermazioni che Good Loop tratti qualcosa.' },
    ],
  },
  'D-16': {
    id: 'D-16',
    title: 'Proprietà intellettuale',
    blocks: [
      { kind: 'p', text: 'La piattaforma Good Loop, i suoi contenuti, il suo design, il suo software e la Metodologia GL, insieme a tutti i materiali, i protocolli, gli esercizi, gli strumenti, le sequenze e la documentazione che esprimono o incorporano la Metodologia GL, sono protetti dal diritto d’autore e da altri diritti di proprietà intellettuale, e gli elementi riservati della Metodologia GL sono protetti come segreti commerciali. Appartengono a Good Loop o sono usati da Good Loop in licenza. La Metodologia GL è stata creata dal suo autore intellettuale, la cui paternità è riconosciuta e preservata.' },
      { kind: 'p', text: 'Ti viene concesso un diritto personale, limitato, revocabile, non esclusivo e non trasferibile di usare Good Loop per il tuo uso personale come consentito da questi Termini. Nulla ti viene ceduto o concesso in licenza oltre a questo.' },
      { kind: 'p', text: 'Non devi copiare, riprodurre, adattare, tradurre, pubblicare, distribuire, vendere, concedere in sublicenza, comunicare al pubblico o rendere disponibile alcuna parte della piattaforma o della Metodologia GL; non devi decompilare, fare ingegneria inversa o tentare di ricavare la struttura o la logica della piattaforma o della Metodologia; non devi usare alcuna parte della piattaforma o della Metodologia per sviluppare, addestrare, valutare o migliorare alcun prodotto, modello o servizio concorrente; e non devi estrarre o raccogliere contenuti dalla piattaforma con alcun mezzo, automatizzato o meno.' },
      { kind: 'p', text: 'Queste restrizioni continuano ad applicarsi dopo che hai smesso di usare Good Loop.' },
    ],
  },
  'D-17': {
    id: 'D-17',
    title: 'Avvisi nel prodotto — requisito essenziale',
    blocks: [
      { kind: 'p', text: 'Ogni schermata di Good Loop dà accesso con un tocco all’aiuto di emergenza tramite il pulsante Aiuto subito, che mostra i numeri di emergenza prima di qualsiasi altra cosa.' },
      { kind: 'p', text: 'La libreria a uso autonomo dichiara in una riga che le sue sessioni sono per il rilassamento e sono raggruppate per momento anziché per condizione. La prima volta che una persona apre una categoria, una breve nota lo ribadisce e, dove è pertinente, rimanda all’aiuto di un professionista. Ogni sessione a uso autonomo termina con un collegamento per trovare un professionista.' },
      { kind: 'p', text: 'Il testo integrale di ogni informativa è disponibile a un tocco di distanza e nella pagina di informazioni legali.' },
      { kind: 'p', text: 'Nessun avviso viene mai attivato, modificato o programmato in base a qualcosa che la persona ha inserito, scelto, valutato o su cui è stata valutata, né in base a un qualsiasi schema del suo uso del servizio. Gli avvisi compaiono in momenti fissi — all’ingresso, al pagamento, alla prenotazione, alla prima visita di una sezione o a una data di calendario — alle stesse condizioni per ogni persona.' },
    ],
  },
  terms: {
    id: 'terms',
    title: 'Termini e condizioni',
    blocks: [
      { kind: 'p', text: 'Versione [1.0] — in vigore dal [data]. Leggi questi Termini prima di usare Good Loop. Stabiliscono che cosa ci impegniamo a fare, che cosa chiediamo a te e che cosa succede se qualcosa va storto. Alcuni di essi limitano ciò che puoi pretendere da noi, e li abbiamo segnalati chiaramente.' },
      { kind: 'h', text: '1. Chi siamo' },
      { kind: 'p', text: '1.1 Good Loop è gestito da [denominazione sociale completa], società costituita in [giurisdizione] con numero di registrazione [•], con sede legale in [•] («Good Loop», «noi»).' },
      { kind: 'p', text: '1.2 Puoi contattarci a [email], tramite la funzione di assistenza nella piattaforma o scrivendoci all’indirizzo sopra indicato. Il nostro responsabile della protezione dei dati è raggiungibile a [email].' },
      { kind: 'h', text: '2. Questi Termini e i documenti che ne fanno parte' },
      { kind: 'p', text: '2.1 Questi Termini sono un contratto tra te e noi. Creando un account, o usando Good Loop, li accetti.' },
      { kind: 'p', text: '2.2 I seguenti documenti fanno parte di questi Termini e sono disponibili nella nostra pagina di informazioni legali: le Informative della piattaforma (da D-01 a D-16), l’Informativa sulla privacy e le eventuali condizioni specifiche di prodotto che ti presentiamo al momento dell’acquisto. Dove il riassunto di uno di essi differisce dal testo integrale, vale il testo integrale.' },
      { kind: 'p', text: '2.3 Se il tuo accesso a Good Loop è pagato da un datore di lavoro o da un’altra organizzazione, si applica a te anche il Supplemento per l’utente finale che, sulle questioni di sponsorizzazione, prevale su questi Termini.' },
      { kind: 'p', text: '2.4 Nulla in questi Termini elimina o limita un diritto che hai in base alla legge sulla tutela dei consumatori del Paese in cui vivi. Dove una clausola di questi Termini contrasta con un tale diritto, si applica quel diritto e la clausola non si applica.' },
      { kind: 'h', text: '3. Definizioni' },
      { kind: 'p', text: '3.1 In questi Termini: «Contenuti» indica tutto ciò che è reso disponibile tramite Good Loop; «Metodologia GL» indica la metodologia psicologica proprietaria descritta nei nostri materiali, insieme a tutto ciò che la esprime o la incorpora; «Professionista» indica una persona abilitata e iscritta a un ordine per fornire servizi psicologici che offre tali servizi tramite Good Loop; «Uso guidato da un professionista» indica l’uso di Good Loop in cui un Professionista dirige l’applicazione della Metodologia GL a te; «Uso autonomo» indica ogni altro uso; «Servizio» indica la piattaforma Good Loop e tutto ciò che forniamo tramite essa; e «Sponsor» indica un’organizzazione che paga il tuo accesso.' },
      { kind: 'h', text: '4. Chi può usare Good Loop' },
      { kind: 'p', text: '4.1 Devi avere almeno diciotto anni e la capacità giuridica di accettare questi Termini. Good Loop non è offerto a bambini o adolescenti.' },
      { kind: 'p', text: '4.2 Good Loop è offerto solo nei territori elencati sul nostro sito, e l’Uso guidato da un professionista è soggetto alle ulteriori restrizioni dell’Informativa sull’ambito territoriale (D-12).' },
      { kind: 'p', text: '4.3 Puoi avere un solo account, ed è personale. Non devi condividerlo e non devi permettere a nessun altro di usarlo.' },
      { kind: 'h', text: '5. Il tuo account' },
      { kind: 'p', text: '5.1 Devi fornirci informazioni accurate quando ti registri e tenerle aggiornate. Poiché Good Loop riguarda il tuo benessere, informazioni inesatte possono portare a un supporto che non si adatta alla tua situazione.' },
      { kind: 'p', text: '5.2 Tieni segrete le tue credenziali. Avvisaci subito se ritieni che qualcun altro abbia avuto accesso al tuo account, e ti aiuteremo a metterlo in sicurezza.' },
      { kind: 'p', text: '5.3 Possiamo richiedere ulteriori verifiche dove ne abbiamo ragionevolmente bisogno — per esempio per confermare l’idoneità al programma di uno Sponsor.' },
      { kind: 'h', text: '6. Che cos’è il Servizio' },
      { kind: 'p', text: '6.1 Good Loop è una piattaforma digitale per il benessere psicologico, offerta in due modi distinti descritti nelle Informative della piattaforma.' },
      { kind: 'p', text: '6.2 Uso autonomo. Quando usi Good Loop senza un Professionista che ti guida, il Servizio è un servizio di benessere pensato per il rilassamento, la riflessione personale e la psicoeducazione. Non è un trattamento, non è una terapia, non diagnostica e non valuta né gestisce alcuna condizione di salute. Vedi D-02 e D-04.' },
      { kind: 'p', text: '6.3 Uso guidato da un professionista. Quando un Professionista lavora con te tramite Good Loop, quel Professionista ti fornisce il servizio psicologico e detiene il rapporto clinico. Noi forniamo la piattaforma, la Metodologia GL e l’ambiente. Vedi D-05 e D-07.' },
      { kind: 'p', text: '6.4 Non è un servizio di emergenza. Good Loop non è monitorato in tempo reale e non deve mai essere usato in un’emergenza o quando qualcuno è a rischio. Vedi D-03.' },
      { kind: 'p', text: '6.5 Good Loop attualmente non include funzioni che usano l’intelligenza artificiale. Se le introdurremo, te lo diremo in anticipo e l’Informativa sulle funzioni automatizzate (D-06) spiegherà come funzionano.' },
      { kind: 'h', text: '7. Licenza e proprietà intellettuale' },
      { kind: 'p', text: '7.1 Ti concediamo un diritto personale, limitato, revocabile, non esclusivo e non trasferibile di usare il Servizio e accedere ai Contenuti per il tuo uso personale in conformità a questi Termini. Tale diritto termina quando termina il tuo accesso.' },
      { kind: 'p', text: '7.2 Tutti i diritti sul Servizio, sui Contenuti e sulla Metodologia GL restano a noi o ai nostri licenzianti, come stabilito nell’Informativa sulla proprietà intellettuale (D-16). Nulla in questi Termini ti trasferisce alcuno di essi.' },
      { kind: 'p', text: '7.3 Non devi copiare, adattare, distribuire, vendere, concedere in sublicenza o pubblicare alcuna parte del Servizio o della Metodologia GL; non devi fare ingegneria inversa o tentare di ricavarne la struttura o la logica; non devi usarne alcuna parte per sviluppare, addestrare, valutare o migliorare alcun prodotto, modello o servizio concorrente; e non devi estrarre o raccogliere Contenuti con alcun mezzo. Queste restrizioni sopravvivono alla cessazione.' },
      { kind: 'p', text: '7.4 Se contribuisci con qualcosa al Servizio — una nota, un messaggio, un feedback — conservi i tuoi diritti su di esso. Ci concedi una licenza per ospitarlo, conservarlo, trasmetterlo e mostrarlo strettamente nella misura necessaria a farti funzionare il Servizio e come descritto nella nostra Informativa sulla privacy. Non usiamo il contenuto delle tue sessioni con un Professionista, né informazioni cliniche su di te, per addestrare modelli di intelligenza artificiale.' },
      { kind: 'p', text: '7.5 Se ci dai un feedback sul Servizio, possiamo usarlo liberamente per migliorare il Servizio, senza obblighi verso di te.' },
      { kind: 'h', text: '8. Uso accettabile' },
      { kind: 'p', text: '8.1 Devi usare Good Loop in modo lecito, rispettoso e per lo scopo a cui è destinato. In particolare non devi:' },
      { kind: 'li', text: '(a) usare il Servizio per ottenere una diagnosi, una prescrizione, una certificazione o qualsiasi determinazione ufficiale;' },
      { kind: 'li', text: '(b) impersonare qualcuno, o dichiarare il falso sulla tua identità, età o idoneità;' },
      { kind: 'li', text: '(c) registrare, fotografare, catturare lo schermo o in altro modo acquisire una sessione, o condividere una tale registrazione;' },
      { kind: 'li', text: '(d) molestare, minacciare, maltrattare o discriminare un Professionista, un membro del nostro team o qualsiasi altra persona;' },
      { kind: 'li', text: '(e) caricare o trasmettere qualcosa di illecito, diffamatorio o che violi i diritti di qualcuno;' },
      { kind: 'li', text: '(f) tentare di ottenere un accesso non autorizzato al Servizio, interromperlo o introdurre codice dannoso;' },
      { kind: 'li', text: '(g) usare mezzi automatizzati per accedere al Servizio, estrarne dati o interagire con esso senza il nostro permesso scritto; oppure' },
      { kind: 'li', text: '(h) rivendere, concedere in sublicenza o sfruttare commercialmente il Servizio o qualsiasi Contenuto.' },
      { kind: 'p', text: '8.2 Possiamo indagare su presunte violazioni e adottare misure proporzionate, che possono comprendere un avvertimento, la limitazione di una funzione, la sospensione o la cessazione. Quando adottiamo una misura te ne spieghiamo il motivo, salvo che la legge ce lo impedisca.' },
      { kind: 'h', text: '9. Segnalazione di contenuti e la nostra risposta' },
      { kind: 'p', text: '9.1 Se trovi nel Servizio contenuti illeciti, dannosi o contrari a questi Termini, segnalali a [email] o tramite la funzione di segnalazione. Dicci qual è il contenuto, dove si trova e perché lo segnali.' },
      { kind: 'p', text: '9.2 Valuteremo ogni segnalazione che riceviamo. Quando una segnalazione è fondata, rimuoveremo o limiteremo l’accesso al contenuto e adotteremo ogni ulteriore misura opportuna. Ti comunicheremo l’esito e, se viene rimosso un tuo contenuto, ti diremo perché e come contestare quella decisione.' },
      { kind: 'p', text: '9.3 Conserviamo una registrazione delle segnalazioni e di ciò che abbiamo fatto al riguardo.' },
      { kind: 'h', text: '10. Servizi guidati da un professionista' },
      { kind: 'p', text: '10.1 Quando prenoti un Professionista tramite Good Loop, nasce un rapporto separato tra te e quel Professionista. Il tuo consenso informato e le eventuali condizioni concordate con il Professionista regolano quel rapporto e, sulle questioni cliniche, prevalgono su questi Termini.' },
      { kind: 'p', text: '10.2 Verifichiamo all’ingresso, e periodicamente in seguito, che ogni Professionista abbia un’iscrizione in corso all’ordine professionale competente. Non garantiamo la competenza clinica di alcun Professionista, la sua adeguatezza per te o alcun esito.' },
      { kind: 'p', text: '10.3 Il Professionista decide se lavorare con te a distanza sia adeguato alla tua situazione, e può rifiutare o indirizzarti altrove. Quella decisione è sua e non la influenziamo.' },
      { kind: 'p', text: '10.4 Le sessioni vanno seguite all’orario programmato. Le nostre regole di cancellazione e spostamento delle sessioni sono pubblicate nella piattaforma e fanno parte di questi Termini; si applicano allo stesso modo a te e al Professionista.' },
      { kind: 'p', text: '10.5 Se un Professionista non è più disponibile, ti aiuteremo a trovare un’alternativa, dove disponibile. Quando un rapporto terapeutico è in corso, sosterremo un passaggio ordinato secondo la clausola 15.4.' },
      { kind: 'h', text: '11. Prezzi, pagamento e abbonamenti' },
      { kind: 'p', text: '11.1 I prezzi sono quelli indicati al momento dell’acquisto, nella valuta indicata, e comprendono le imposte applicabili salvo diversa indicazione.' },
      { kind: 'p', text: '11.2 Se acquisti un abbonamento, prima dell’acquisto ti diremo chiaramente: che cosa ottieni, il prezzo, il periodo di fatturazione, che l’abbonamento si rinnova automaticamente, il prezzo al rinnovo e come interromperlo. La tua accettazione del rinnovo automatico è raccolta separatamente dalla tua accettazione di questi Termini.' },
      { kind: 'p', text: '11.3 Un abbonamento si rinnova automaticamente alla fine di ogni periodo di fatturazione al prezzo che ti è stato comunicato, salvo che tu disdica prima della data di rinnovo. Ti ricorderemo ogni rinnovo dove la legge lo richiede, e in ogni caso prima di ogni rinnovo di un periodo superiore a un mese.' },
      { kind: 'p', text: '11.4 Se cambiamo il prezzo del tuo abbonamento, te lo diremo almeno [trenta] giorni prima che la modifica abbia effetto e potrai disdire prima. Una modifica di prezzo non si applica mai a un periodo che hai già pagato.' },
      { kind: 'p', text: '11.5 Se un pagamento non va a buon fine te lo diremo e potremo sospendere l’accesso finché non viene risolto. Non cesseremo il Servizio per un pagamento non riuscito senza darti una ragionevole possibilità di rimediare.' },
      { kind: 'p', text: '11.6 I pagamenti sono gestiti da [fornitore di pagamento]. Le sue condizioni regolano l’elaborazione del tuo pagamento, e noi non conserviamo i dati completi della tua carta.' },
      { kind: 'h', text: '12. Disdetta e ripensamento' },
      { kind: 'p', text: '12.1 Puoi disdire un abbonamento in qualsiasi momento, con effetto alla fine del periodo di fatturazione in corso, dalle impostazioni del tuo account. Disdire non deve mai essere più difficile che abbonarsi; se scopri che lo è, diccelo e lo disdiremo noi per te.' },
      { kind: 'p', text: '12.2 Diritto di ripensamento previsto dalla legge. Hai il diritto, previsto dalla legge, di recedere da un contratto a distanza, in aggiunta al diritto di disdetta della clausola 12.1. Il periodo e le modalità cambiano da Paese a Paese e sono indicati nell’allegato che si applica a te:' },
      { kind: 'li', text: '(a) se vivi in Brasile, si applica l’Allegato I e il periodo è di sette giorni; e' },
      { kind: 'li', text: '(b) se vivi in uno Stato membro dell’Unione europea, si applica l’Allegato II e il periodo è di quattordici giorni.' },
      { kind: 'p', text: 'Ai sensi dell’articolo 49 del Codice di difesa del consumatore, poiché hai contratto fuori dai nostri locali commerciali, puoi recedere da questo contratto entro sette giorni dalla data in cui hai contratto o da quella in cui hai avuto accesso per la prima volta al Servizio, se successiva, senza indicare alcun motivo.', market: 'BR' },
      { kind: 'p', text: 'Per recedere, comunicacelo a [email] o tramite la piattaforma. Ti rimborseremo ogni importo pagato, rivalutato, immediatamente, con lo stesso mezzo di pagamento che hai usato. Non devi dare alcuna motivazione e non ti addebiteremo nulla per il recesso.', market: 'BR' },
      { kind: 'p', text: 'Hai quattordici giorni dal giorno della conclusione del contratto per recedere, senza indicare alcun motivo.', market: 'EU' },
      { kind: 'p', text: 'Per recedere, comunicacelo con una dichiarazione esplicita — è sufficiente un’email a [email] — oppure usa il modulo tipo di recesso disponibile nella nostra pagina di informazioni legali. È sufficiente che tu invii la comunicazione prima della scadenza dei quattordici giorni.', market: 'EU' },
      { kind: 'p', text: 'Ti rimborseremo tutti i pagamenti ricevuti da te entro quattordici giorni da quando ne siamo informati, con lo stesso mezzo di pagamento che hai usato, senza alcun costo per te.', market: 'EU' },
      { kind: 'p', text: 'Se ci hai chiesto di iniziare a fornire il Servizio durante il periodo di recesso e poi recedi, paghi solo un importo proporzionale a quanto è stato fornito fino al momento in cui ce lo hai comunicato.', market: 'EU' },
      { kind: 'p', text: '12.3 Per recedere, comunicacelo entro il periodo applicabile con una dichiarazione esplicita — è sufficiente un’email — o con il modulo fornito nell’allegato pertinente. Rimborseremo quanto dovuto entro il periodo indicato in quell’allegato, con lo stesso mezzo di pagamento che hai usato.' },
      { kind: 'p', text: '12.4 Al di fuori del periodo previsto dalla legge, si applica la nostra politica di rimborso pubblicata nella piattaforma. Quella politica non riduce, e non può ridurre, i tuoi diritti di legge.' },
      { kind: 'h', text: '13. Modifiche al Servizio' },
      { kind: 'p', text: '13.1 Miglioriamo il Servizio in modo continuo e possiamo aggiungere, modificare o rimuovere funzioni. Non apporteremo una modifica che riduca in modo sostanziale ciò per cui hai pagato durante un periodo già pagato.' },
      { kind: 'p', text: '13.2 Se apportiamo una modifica che ti danneggia in modo sostanziale, te lo diremo in anticipo e potrai recedere ricevendo un rimborso proporzionale di quanto pagato per il periodo non goduto.' },
      { kind: 'h', text: '14. Disponibilità' },
      { kind: 'p', text: '14.1 Lavoriamo per mantenere il Servizio disponibile, ma può essere interrotto per manutenzione, per ragioni tecniche o per eventi fuori dal nostro controllo. Daremo avviso della manutenzione programmata dove ragionevolmente possibile.' },
      { kind: 'p', text: '14.2 Il Servizio dipende dal tuo dispositivo, dal tuo software e dalla tua connessione internet, che sono responsabilità tua.' },
      { kind: 'h', text: '15. Sospensione, cessazione e continuità' },
      { kind: 'p', text: '15.1 Puoi chiudere il tuo account in qualsiasi momento.' },
      { kind: 'p', text: '15.2 Possiamo sospendere o cessare il tuo accesso se violi in modo sostanziale questi Termini, se la legge ce lo impone, o se continuare a fornire il Servizio esporrebbe te o un’altra persona a un rischio grave. Salvo che la violazione sia grave o la legge richieda un’azione immediata, ti daremo un preavviso e la possibilità di rimediare.' },
      { kind: 'p', text: '15.3 Alla cessazione termina il tuo diritto di usare il Servizio. Gestiremo i tuoi dati personali come descritto nella nostra Informativa sulla privacy e conserveremo solo ciò che la legge ci impone di conservare.' },
      { kind: 'p', text: '15.4 Continuità della cura. Quando un rapporto terapeutico con un Professionista è in corso e il tuo accesso sta per terminare per qualsiasi motivo, te lo diremo in anticipo, informeremo il Professionista perché possa adempiere ai propri obblighi verso di te, e sosterremo una conclusione o un passaggio ordinato. Non interromperemo bruscamente un rapporto terapeutico quando è in nostro potere evitarlo.' },
      { kind: 'p', text: '15.5 Le clausole 7, 16, 17, 20, 23 e ogni altra clausola che per sua natura debba continuare sopravvivono alla cessazione.' },
      { kind: 'h', text: '16. La nostra responsabilità verso di te' },
      { kind: 'p', text: 'Siamo responsabili di fornire il Servizio con la qualità, la sicurezza e l’adeguatezza che puoi legittimamente aspettarti, in conformità al Codice di difesa del consumatore. Non escludiamo, non riduciamo e non trasferiamo tale responsabilità, e nulla in questi Termini va letto come un tentativo di farlo.', market: 'BR' },
      { kind: 'p', text: 'Ciò che ci impegniamo a fornire è descritto nella clausola 6 e nelle Informative della piattaforma. Nell’uso autonomo forniamo un servizio di benessere; non forniamo trattamento, diagnosi o cure cliniche, e non affermiamo di farlo. Quando un Professionista guida il tuo uso di Good Loop, quel Professionista fornisce il servizio psicologico ed è responsabile dei propri atti clinici, come descritto in D-05 e D-07, mentre noi restiamo responsabili del funzionamento e della sicurezza della piattaforma come descritto e della verifica dell’iscrizione del Professionista come descritto nella clausola 10.2.', market: 'BR' },
      { kind: 'p', text: 'Se il Servizio è difettoso, hai i diritti che ti dà il Codice di difesa del consumatore, tra cui la riparazione del difetto, la sostituzione del servizio, una riduzione proporzionale del prezzo o la restituzione dell’importo pagato, rivalutato, oltre al risarcimento di ogni danno subito. Comunicacelo a [email] e ce ne occuperemo.', market: 'BR' },
      { kind: 'p', text: '16.1 Forniremo il Servizio con ragionevole cura e competenza.', market: 'EU' },
      { kind: 'p', text: '16.2 Siamo responsabili delle perdite che subisci come conseguenza prevedibile di una nostra violazione di questi Termini o della nostra mancanza di ragionevole cura e competenza. Non siamo responsabili di perdite non prevedibili.', market: 'EU' },
      { kind: 'p', text: '16.3 Non escludiamo né limitiamo in alcun modo la nostra responsabilità dove sarebbe illecito farlo. Ciò comprende la responsabilità per morte o lesioni personali causate dalla nostra negligenza, per frode o dichiarazioni fraudolente, per qualsiasi violazione dei tuoi diritti di consumatore previsti dalla legge e per qualsiasi responsabilità che non può essere esclusa in base alla legge sulla protezione dei dati che si applica a te.', market: 'EU' },
      { kind: 'p', text: '16.4 Fatta salva la clausola 16.3, la nostra responsabilità complessiva verso di te in relazione al Servizio in qualsiasi periodo di dodici mesi è limitata al maggiore tra l’importo che ci hai pagato in quel periodo e [500 EUR].', market: 'EU' },
      { kind: 'p', text: '16.5 Non siamo responsabili del contenuto clinico, della qualità o dell’esito di ciò che un Professionista decide nel tuo caso, che è responsabilità del Professionista come descritto in D-05 e D-07. Ciò non incide sulla nostra responsabilità per la verifica dell’iscrizione come descritto nella clausola 10.2, né per il funzionamento e la sicurezza del Servizio.', market: 'EU' },
      { kind: 'p', text: '16.6 Non siamo responsabili di siti web, applicazioni o servizi di terzi, come descritto in D-14.', market: 'EU' },
      { kind: 'p', text: '16.7 Forniamo il Servizio per uso personale. Non abbiamo alcuna responsabilità verso di te per perdita di profitto, perdita di affari, interruzione di attività o perdita di opportunità commerciali.', market: 'EU' },
      { kind: 'h', text: '17. La tua responsabilità verso di noi' },
      { kind: 'p', text: '17.1 Se usi il Servizio in modo illecito, o in grave violazione della clausola 8, e ne subiamo una perdita, ne sei responsabile nella misura consentita dalla legge.' },
      { kind: 'h', text: '18. I tuoi dati personali' },
      { kind: 'p', text: '18.1 Trattiamo i tuoi dati personali come descritto nella nostra Informativa sulla privacy, che fa parte di questi Termini.' },
      { kind: 'p', text: '18.2 Le informazioni sulla tua salute mentale sono sensibili e sono trattate come tali. Quando un Professionista lavora con te, la documentazione clinica è tenuta da quel Professionista secondo i propri obblighi professionali, e noi non la usiamo per i nostri scopi.' },
      { kind: 'p', text: '18.3 Hai dei diritti sui tuoi dati personali, tra cui i diritti di accesso, rettifica, cancellazione, portabilità e opposizione. L’Informativa sulla privacy spiega come esercitarli e come contattare il nostro responsabile della protezione dei dati e, se vuoi, l’autorità di controllo.' },
      { kind: 'h', text: '19. Se qualcosa va storto' },
      { kind: 'p', text: '19.1 Diccelo prima di tutto. Scrivi a [email]: confermeremo la ricezione entro [due] giorni lavorativi e risponderemo nel merito entro [dieci] giorni lavorativi, dicendoti che cosa abbiamo accertato e che cosa proponiamo di fare.' },
      { kind: 'p', text: '19.2 Se non sei soddisfatto, puoi andare oltre. Nulla in questi Termini ti obbliga a usare la nostra procedura di reclamo prima di esercitare un diritto, e nulla ti obbliga a ricorrere all’arbitrato.' },
      { kind: 'p', text: '19.3 Quando un reclamo riguarda la condotta di un Professionista, puoi anche rivolgerti al suo ordine professionale. Ti daremo i suoi contatti su richiesta.' },
      { kind: 'p', text: '19.4 L’allegato che si applica a te indica gli organismi di tutela dei consumatori e le vie di risoluzione delle controversie disponibili nel tuo Paese.' },
      { kind: 'h', text: '20. Legge applicabile e foro' },
      { kind: 'p', text: 'Questi Termini sono regolati dalla legge brasiliana, in particolare dal Codice di difesa del consumatore (Lei 8.078/1990), dalla Legge generale sulla protezione dei dati (Lei 13.709/2018) e dal Quadro civile di internet (Lei 12.965/2014).', market: 'BR' },
      { kind: 'p', text: 'Puoi avviare qualsiasi procedimento presso il tribunale del tuo domicilio, e nulla in questi Termini lo limita.', market: 'BR' },
      { kind: 'p', text: 'Questi Termini non contengono alcuna clausola arbitrale. Non sei tenuto ad arbitrare alcuna controversia con noi, e nulla in questi Termini rinuncia al tuo diritto di partecipare a un’azione collettiva.', market: 'BR' },
      { kind: 'p', text: 'Prima di rivolgerti a un tribunale puoi, se vuoi, usare il nostro canale di reclamo, contattare il PROCON del tuo Stato o usare la piattaforma federale per i consumatori consumidor.gov.br. Sono opzioni a tua disposizione, non condizioni da soddisfare.', market: 'BR' },
      { kind: 'p', text: 'Questi Termini sono regolati dalla legge dello Stato membro in cui risiedi abitualmente.', market: 'EU' },
      { kind: 'p', text: 'Puoi avviare un procedimento presso i tribunali di quello Stato membro, e noi avvieremo qualsiasi procedimento contro di te solo lì.', market: 'EU' },
      { kind: 'p', text: 'Puoi anche usare la piattaforma europea di risoluzione delle controversie online o qualsiasi organismo di risoluzione alternativa delle controversie applicabile nel tuo Paese. I dettagli sono nella nostra pagina di informazioni legali. Usarli è facoltativo.', market: 'EU' },
      { kind: 'h', text: '21. Modifiche a questi Termini' },
      { kind: 'p', text: '21.1 Possiamo modificare questi Termini. Ti avviseremo almeno [trenta] giorni prima che una modifica che ti riguarda in modo sostanziale abbia effetto, via email e nella piattaforma, e pubblicheremo che cosa è cambiato.' },
      { kind: 'p', text: '21.2 Se non accetti una modifica puoi recedere prima che abbia effetto e ricevere un rimborso proporzionale di quanto pagato per il periodo non goduto. Continuare a usare il Servizio dopo che la modifica ha effetto significa accettarla.' },
      { kind: 'p', text: '21.3 Manteniamo disponibili le versioni precedenti di questi Termini nella nostra pagina di informazioni legali, con la data in cui ciascuna è stata in vigore.' },
      { kind: 'p', text: '21.4 Non modificheremo questi Termini in modo retroattivo, e non li modificheremo unilateralmente in un modo che riduca ciò per cui hai già pagato.' },
      { kind: 'h', text: '22. Cessione del contratto' },
      { kind: 'p', text: '22.1 Possiamo trasferire i nostri diritti e obblighi in base a questi Termini a un’altra organizzazione, per esempio in caso di riorganizzazione o cessione dell’attività. Te lo diremo se lo faremo, e il trasferimento non ridurrà i tuoi diritti. Se non vuoi continuare, puoi recedere e ricevere un rimborso proporzionale di quanto pagato per il periodo non goduto.' },
      { kind: 'p', text: '22.2 Non puoi trasferire i tuoi diritti o obblighi a nessun altro.' },
      { kind: 'h', text: '23. Disposizioni generali' },
      { kind: 'p', text: '23.1 Nullità parziale. Se una clausola di questi Termini è ritenuta invalida o inapplicabile, le altre restano in vigore, e la clausola invalida è sostituita da una valida che si avvicini il più possibile al suo scopo.' },
      { kind: 'p', text: '23.2 Nessuna rinuncia. Se non facciamo valere subito un diritto, non lo perdiamo.' },
      { kind: 'p', text: '23.3 Intero accordo. Questi Termini, insieme ai documenti che incorporano, costituiscono l’intero accordo tra noi sul Servizio. Ciò non esclude la responsabilità per qualcosa che abbiamo detto in modo disonesto, né incide sulle dichiarazioni che ci vincolano in base alla legge sui consumatori.' },
      { kind: 'p', text: '23.4 Lingua. Questi Termini sono pubblicati in [portoghese / italiano / inglese]. La versione [portoghese] fa fede per gli utenti in Brasile e la versione [italiana] fa fede per gli utenti in Italia. Le altre versioni linguistiche sono fornite per comodità.' },
      { kind: 'p', text: '23.5 Eventi fuori dal nostro controllo. Non siamo responsabili di un inadempimento la cui causa è fuori dal nostro ragionevole controllo, ma te lo diremo e non ti addebiteremo un servizio che non possiamo fornire.' },
      { kind: 'p', text: '23.6 Versione. Questa è la versione [1.0], in vigore dal [data].' },
    ],
  },
  supplement: {
    id: 'supplement',
    title: 'Supplemento per l’utente finale — accesso sponsorizzato',
    blocks: [
      { kind: 'h', text: 'S1. Perché stai leggendo questo' },
      { kind: 'p', text: 'Il tuo accesso a Good Loop è pagato dal tuo datore di lavoro o da un’altra organizzazione (il tuo «Sponsor»). Questo Supplemento spiega che cosa significa. Si aggiunge ai Termini e condizioni e, dove i due differiscono su qualcosa che riguarda il tuo Sponsor, si applica questo Supplemento.' },
      { kind: 'h', text: 'S2. Il tuo Sponsor non è parte del tuo uso di Good Loop' },
      { kind: 'p', text: 'Il tuo Sponsor ha un accordo commerciale con noi. Non è parte dell’accordo tra te e noi, e non ha alcun diritto sul tuo account, sulle tue informazioni o sulla tua cura.' },
      { kind: 'h', text: 'S3. Che cosa il tuo Sponsor non riceve mai' },
      { kind: 'p', text: 'L’Informativa sulla riservatezza verso datore di lavoro e sponsor (D-08) fa parte di questo Supplemento ed è un impegno vincolante che prendiamo con te. In sintesi: il tuo Sponsor non riceverà mai se, quando o quanto spesso hai usato Good Loop, che cosa hai fatto, qualsiasi cosa tu abbia scritto, se hai prenotato o seguito una sessione, chi hai incontrato, che cosa è stato discusso, o qualsiasi cosa da cui una di queste possa ragionevolmente essere dedotta.' },
      { kind: 'h', text: 'S4. Che cosa riceve il tuo Sponsor' },
      { kind: 'p', text: 'Informazioni aggregate e prive di elementi identificativi sul programma nel suo insieme, mai derivate da un gruppo inferiore a [venticinque] persone. I dati sotto quella soglia vengono nascosti, non comunicati.' },
      { kind: 'h', text: 'S5. Il tuo Sponsor non può chiederti di rinunciare a questa tutela' },
      { kind: 'p', text: 'Il nostro accordo con il tuo Sponsor gli impone di non chiedere informazioni individuali su di te, di non chiederti di rivelare il tuo uso di Good Loop e di non trattarti in modo diverso perché lo hai usato o perché non lo hai fatto. Se ritieni che il tuo Sponsor abbia fatto una di queste cose, comunicacelo a [email]. Puoi anche segnalarlo all’autorità di protezione dei dati del tuo Paese.' },
      { kind: 'h', text: 'S6. Se la sponsorizzazione termina' },
      { kind: 'p', text: 'Se il tuo Sponsor smette di pagare, o se lasci l’organizzazione, ti daremo almeno [trenta] giorni di preavviso prima che il tuo accesso cambi. Ti diremo che cosa succede alle tue informazioni e, dove è disponibile un’opzione di continuazione, ti spiegheremo come attivarla. Se in quel momento stai lavorando con un Professionista, si applica la clausola 15.4 dei Termini e sosterremo una conclusione o un passaggio ordinato.' },
      { kind: 'h', text: 'S7. Usare Good Loop è una tua scelta' },
      { kind: 'p', text: 'Il tuo Sponsor può metterti a disposizione Good Loop, ma non può obbligarti a usarlo, e scegliere di non usarlo non è una questione che riguarda il tuo Sponsor.' },
    ],
  },
  professional: {
    id: 'professional',
    title: 'Termini per i professionisti',
    blocks: [
      { kind: 'h', text: 'P1. Status e indipendenza' },
      { kind: 'p', text: 'P1.1 Il Professionista è un prestatore indipendente, non un dipendente di Good Loop, ed esercita un giudizio professionale indipendente. Non si crea alcun rapporto di agenzia o società.' },
      { kind: 'p', text: 'P1.2 Good Loop non dirige le decisioni cliniche. Qualsiasi suggerimento generato dalla piattaforma, anche da una funzione automatizzata, è puramente indicativo e può essere ignorato.' },
      { kind: 'h', text: 'P2. Iscrizione e competenza' },
      { kind: 'p', text: 'P2.1 Il Professionista garantisce di essere iscritto all’ordine professionale competente, di essere autorizzato a esercitare nel territorio da cui esercita e nei confronti delle persone che assiste, che nessun procedimento disciplinare è pendente a suo carico, e che informerà Good Loop immediatamente se una di queste cose cambia.' },
      { kind: 'p', text: 'P2.2 Il Professionista è responsabile di valutare se l’erogazione a distanza, e l’applicazione della Metodologia GL, siano adeguate a ciascuna persona, e di rifiutare o inviare altrove quando non lo sono — in conformità alla Risoluzione CFP 9/2024 in Brasile e alle linee guida CNOP in Italia.' },
      { kind: 'p', text: 'P2.3 Il Professionista deve rispettare i requisiti territoriali delle proprie regole professionali, compreso l’eventuale obbligo di esercitare da un dato territorio o da una connessione ivi registrata.' },
      { kind: 'p', text: 'P2.4 Good Loop verifica l’iscrizione all’ingresso e periodicamente in seguito, e può sospendere un Professionista in attesa di verifica.' },
      { kind: 'h', text: 'P3. Responsabilità clinica e documentazione' },
      { kind: 'p', text: 'P3.1 Il Professionista detiene il rapporto clinico e ne porta la responsabilità clinica e professionale.' },
      { kind: 'p', text: 'P3.2 Il Professionista è responsabile di raccogliere un consenso informato che copra, come minimo: la natura e lo scopo dell’intervento; il fatto che sia erogato a distanza e che cosa comporti; i limiti del mezzo e che cosa succede se la connessione cade; la riservatezza e i suoi limiti; come è tenuta la documentazione, dove, per quanto tempo e chi può accedervi; le disposizioni in caso di rischio per la persona; onorari e cancellazioni; e le alternative al lavoro a distanza. Il Professionista deve documentare quel consenso.' },
      { kind: 'p', text: 'P3.3 Il Professionista tiene la documentazione professionale richiesta dal proprio ordine e ne è il titolare. Good Loop non la usa per i propri scopi.' },
      { kind: 'p', text: 'P3.4 Il Professionista deve attenersi alla procedura di escalation pubblicata da Good Loop quando una persona rivela un rischio, fermi restando il proprio giudizio e i propri doveri professionali, che prevalgono.' },
      { kind: 'p', text: 'P3.5 Quando un rapporto terapeutico deve terminare, il Professionista deve concluderlo o trasferirlo secondo i propri obblighi professionali, e non deve interromperlo bruscamente.' },
      { kind: 'h', text: 'P4. Metodologia, riservatezza e proprietà intellettuale' },
      { kind: 'p', text: 'P4.1 Al Professionista è concessa una licenza limitata, revocabile e non esclusiva per usare la libreria di contenuti Good Loop esclusivamente nella cura che egli stesso fornisce tramite Good Loop, e per nessun altro scopo. Il Professionista sceglie quali contenuti usare e quando; Good Loop non prescrive alcuna sequenza e non presenta la libreria come un protocollo o un percorso di trattamento.' },
      { kind: 'p', text: 'P4.2 Il Professionista non deve divulgare, riprodurre, insegnare, pubblicare o sfruttare commercialmente la Metodologia GL; non deve usarla al di fuori di Good Loop; non deve usarla, né alcun risultato della piattaforma, per sviluppare, addestrare o valutare alcun prodotto, modello o servizio concorrente; e deve restituire o distruggere tutti i materiali alla cessazione. Questi obblighi sopravvivono alla cessazione a tempo indeterminato per gli elementi riservati.' },
      { kind: 'p', text: 'P4.3 Il Professionista non deve registrare le sessioni se non con il consenso separato e documentato della persona, dove le regole professionali lo permettono, e non deve condividere alcuna registrazione.' },
      { kind: 'p', text: 'P4.4 Il Professionista deve mantenere riservate tutte le informazioni sulle persone assistite e sull’attività di Good Loop.' },
      { kind: 'p', text: 'P4.5 Il Professionista riconosce di essere l’unico soggetto curante, che il giudizio clinico su se e come usare i contenuti è suo, e che non descriverà Good Loop ad alcuna persona assistita come fornitore del trattamento o come esecutore di un protocollo terapeutico.' },
      { kind: 'h', text: 'P5. Assicurazione, manleva e cessazione' },
      { kind: 'p', text: 'P5.1 Il Professionista deve avere un’assicurazione di responsabilità professionale non inferiore a [importo] e fornirne prova su richiesta.' },
      { kind: 'p', text: 'P5.2 Il Professionista manleva Good Loop dalle pretese derivanti dai propri atti e omissioni clinici, dalla violazione di questi termini e dalla violazione dei propri obblighi professionali.' },
      { kind: 'p', text: 'P5.3 Good Loop può sospendere o cessare il rapporto con effetto immediato se l’iscrizione decade, se viene avviato un procedimento disciplinare o se esiste un rischio grave per una persona assistita — fermo restando in ogni caso l’obbligo di continuità di cui a P3.5.' },
    ],
  },
}
