/* ============================================================================
   Good Loop — legal texts, ENGLISH WORKING MASTER

   Generated verbatim from GoodLoop_Disclaimers_and_Terms_v5_PathA.docx
   (Part IV disclaimers D-01 to D-17, Part V.A Terms with the Annex I / II
   substitutions for clauses 12.2, 16 and 20, Part V.B End-User Supplement,
   Part V.D Professional Terms). Do not edit the wording here by hand: the
   deliverable is the source, this file is its rendering. Bracketed items
   — [like this] — are corporate facts counsel completes before publication.

   English is the working master. The Portuguese and Italian versions in
   legal-pt.ts / legal-it.ts are FIRST DRAFTS for counsel in each market,
   which designates them as governing (Part VI.4). Blocks tagged with a
   market are the annex text that REPLACES the corresponding clause in that
   market; untagged blocks apply everywhere.
   ============================================================================ */

import type { LegalDocText } from './types'

export const LEGAL_EN: Record<string, LegalDocText> = {
  "D-01": {
    id: "D-01",
    title: "Important — please read before using Good Loop",
    blocks: [
      { kind: "p", text: "Good Loop is a digital platform for psychological wellbeing. It is offered in two distinct ways, and your rights and our responsibilities differ depending on which one applies to you." },
      { kind: "p", text: "When you use Good Loop on your own, without a professional guiding you, Good Loop is a wellbeing service. It is intended for relaxation, self-reflection and learning about psychological wellbeing. It is not treatment, it is not therapy, and it does not assess, diagnose or manage any health condition." },
      { kind: "p", text: "When a licensed professional uses Good Loop to guide you, that professional — and not Good Loop — provides the psychological service to you. The professional is responsible for the clinical decisions taken, for the suitability of the approach to your situation, and for their own professional and ethical obligations. Good Loop provides the technology, the methodology and the environment in which that service is delivered." },
      { kind: "p", text: "Good Loop is not an emergency service and must never be used in an emergency. If you are at risk, or you believe someone else is at risk, stop and seek immediate help — see our Crisis and Emergency Notice." },
      { kind: "p", text: "The following notices form part of these Terms and apply to your use of Good Loop: the Nature of the Service Notice; the Crisis and Emergency Notice; the Self-Guided Use Notice; the Professionally Guided Use Notice; the Automated Features Notice; the Confidentiality and Data Notice; and the other notices published on our legal information page. Please read them. If there is any conflict between a summary of a notice and its full text, the full text applies." },
      { kind: "p", text: "If you do not agree with these notices, please do not use Good Loop." },
    ],
  },
  "D-02": {
    id: "D-02",
    title: "Nature of the service and intended use",
    blocks: [
      { kind: "h", text: "Intended use" },
      { kind: "p", text: "Good Loop’s software provides pre-recorded audio content and session-organisation tooling to adults aged eighteen and over, in two ways: (i) as a self-guided wellbeing resource offering relaxation, self-reflection and psychoeducational content; and (ii) as a library of content and tools from which a licensed professional independently selects, and which that professional may use within care that they design, deliver and remain clinically responsible for." },
      { kind: "h", text: "What Good Loop is not" },
      { kind: "p", text: "Good Loop is not a medical device. It does not diagnose, treat, cure, prevent, monitor or predict any disease, disorder or clinical condition. It does not determine, and does not purport to determine, whether you have any condition, how severe it is, or what care you should receive. It does not select, sequence, recommend or adapt content on the basis of anything about you. Good Loop does not prescribe and gives no guidance on medication; if anything within the platform ever appears to do so, disregard it and tell us." },
      { kind: "p", text: "Good Loop is not a substitute for professional medical, psychiatric or psychological advice, diagnosis or treatment. Always seek the advice of a qualified health professional with any question you have about your health or your mental health. Never disregard professional advice, and never delay seeking it, because of anything you have read, seen or done on Good Loop. Never start, stop or change any medication because of Good Loop." },
      { kind: "p", text: "Good Loop is not suitable for, and is not offered for use in, a mental health crisis, an emergency, or a situation of risk to yourself or to any other person. Good Loop is not suitable for people with severe or enduring mental illness who require specialist care, and is not designed for use where clinical assessment in person is needed." },
      { kind: "p", text: "Good Loop is not to be used to obtain any official determination, certification, report or documentation — including for court, employment, insurance, immigration or benefit purposes — and no output of the platform should be presented or relied upon for any such purpose." },
      { kind: "h", text: "How our content is organised" },
      { kind: "p", text: "Our sessions are grouped by the situation you may be in — a working day, a journey, the end of an evening — so that you can find one that suits the moment. This grouping describes a circumstance and nothing else. It is not an indication, it is not a statement about any condition, and no session is offered to you on the basis of anything we know or assume about your health." },
      { kind: "h", text: "Who it is for" },
      { kind: "p", text: "Good Loop is offered to adults aged eighteen and over, in the territories where we state that it is available. It is not offered to children or adolescents." },
    ],
  },
  "D-03-BR": {
    id: "D-03-BR",
    title: "If you are at risk, do not use Good Loop — get help now",
    blocks: [
      { kind: "p", text: "Good Loop is not an emergency service, is not monitored in real time, and cannot help you in a crisis." },
      { kind: "p", text: "If you are thinking about ending your life, thinking about harming yourself or another person, or if you believe that you or anyone else is in danger, stop using Good Loop and get help immediately:" },
      { kind: "p", text: "Emotional support and suicide prevention — CVV: call 188 (free, 24 hours) or visit cvv.org.br" },
      { kind: "p", text: "Medical emergency — SAMU: call 192.  Police and general emergency: call 190." },
      { kind: "p", text: "Or go to the nearest hospital emergency department, or a UPA or CAPS unit near you." },
      { kind: "p", text: "If you are with someone who is at risk, do not leave them alone and call for help." },
      { kind: "p", text: "Nothing on Good Loop — including any message you send within the platform, to a professional, or to any automated feature — will be treated as a request for emergency assistance, and no such message will produce an emergency response. Messages sent to a professional are not read in real time and may not be seen until that professional’s next working period." },
    ],
  },
  "D-03-EU": {
    id: "D-03-EU",
    title: "If you are at risk, do not use Good Loop — get help now",
    blocks: [
      { kind: "p", text: "Good Loop is not an emergency service, is not monitored in real time, and cannot help you in a crisis." },
      { kind: "p", text: "If you are thinking about ending your life, thinking about harming yourself or another person, or if you believe that you or anyone else is in danger, stop using Good Loop and get help immediately:" },
      { kind: "p", text: "Emergency services — call 112, the single European emergency number, free from any telephone." },
      { kind: "p", text: "Or go to the nearest hospital emergency department." },
      { kind: "p", text: "[Insert here the verified national crisis and emotional-support helpline for each country in which the service is offered, with its name, number, hours and website.]" },
      { kind: "p", text: "If you are with someone who is at risk, do not leave them alone and call for help." },
      { kind: "p", text: "Nothing on Good Loop — including any message you send within the platform, to a professional, or to any automated feature — will be treated as a request for emergency assistance, and no such message will produce an emergency response." },
    ],
  },
  "D-04": {
    id: "D-04",
    title: "When you use Good Loop on your own",
    blocks: [
      { kind: "p", text: "You are using Good Loop on your own whenever you access its content, exercises or tools without a licensed professional guiding your use of them. Most of what follows is common sense, but it matters and we want to be clear about it." },
      { kind: "h", text: "What self-guided use is for" },
      { kind: "p", text: "Relaxation. Rest. Noticing and reflecting on how you feel. Learning about psychological wellbeing in general terms. Building everyday habits that many people find helpful. That is the whole of it, and for many people it is genuinely useful." },
      { kind: "h", text: "What self-guided use is not" },
      { kind: "p", text: "It is not therapy. It is not treatment. It is not a clinical intervention, and it is not a course of care. Nothing you do on your own within Good Loop is directed at any condition you may have, because Good Loop does not know and does not attempt to determine whether you have one. No exercise, technique or piece of content offered to you in self-guided use has been selected because of any assessment of your health." },
      { kind: "p", text: "The GL Methodology is a psychological methodology. In self-guided use you are being offered general wellbeing content that draws on it. You are not receiving the Methodology as a treatment, because the Methodology is applied as a treatment only by a qualified professional who knows your situation and takes responsibility for that application." },
      { kind: "h", text: "Why sessions are grouped by situation" },
      { kind: "p", text: "Some sessions are made for a particular moment — before a flight, between meetings, at the end of the day. That is because relaxation works better when it fits the circumstances you are actually in: how much time you have, whether you can close your eyes, whether you are sitting in a confined space. Grouping sessions this way is about the moment, not about you. It does not mean we think you have any condition, and choosing a session does not tell us anything about your health." },
      { kind: "h", text: "If you need more than this" },
      { kind: "p", text: "If you are struggling, if something is not improving, or if you are unsure whether self-guided use is enough for you, please speak to a qualified professional. You can arrange professionally guided support through Good Loop where that is available to you, or seek help independently. Please do not use self-guided content as a reason to postpone getting help you may need." },
    ],
  },
  "D-05": {
    id: "D-05",
    title: "When a professional guides your use of Good Loop",
    blocks: [
      { kind: "p", text: "Where a licensed professional works with you through Good Loop, the psychological service is provided to you by that professional. The professional is independent. Good Loop supplies audio content and the tools to organise sessions; the professional decides what is used, when, and whether it suits you at all. Good Loop does not provide the psychological service, does not participate in your care, and does not recommend, sequence or adapt anything for you." },
      { kind: "h", text: "What the professional is responsible for" },
      { kind: "p", text: "The professional is responsible for deciding whether working with you at a distance is appropriate to your situation at all; for the clinical judgement exercised in your case; for selecting, adapting and applying the GL Methodology or any other approach to you; for keeping the professional record required by their regulator; for their own professional secrecy; and for compliance with the rules of the professional body with which they are registered. Those decisions are theirs and Good Loop neither makes them nor overrides them." },
      { kind: "h", text: "What Good Loop is responsible for" },
      { kind: "p", text: "Good Loop is responsible for the platform functioning as described, for the content being as we describe it, for verifying at onboarding and periodically thereafter that each professional holds a current registration with the relevant professional body, and for the security of the environment. Good Loop is not responsible for the clinical content, quality or outcome of what a professional decides in your case — including which content they choose and how they use it." },
      { kind: "h", text: "What we do not verify" },
      { kind: "p", text: "We verify professional registration. We do not warrant any professional’s clinical skill, their suitability for you, or the outcome of working with them. If a professional is not right for you, tell us and we will help you change; if you believe a professional has acted improperly, tell us and you may also complain to their professional body, whose contact details we will provide." },
      { kind: "h", text: "Your agreement with the professional" },
      { kind: "p", text: "Your relationship with the professional is governed by the informed consent and any service terms agreed directly between you and them, in addition to these Terms. Where those documents address the clinical relationship, they prevail over these Terms on that subject." },
    ],
  },
  "D-06": {
    id: "D-06",
    title: "Automated features and artificial intelligence",
    blocks: [
      { kind: "p", text: "Good Loop does not currently use artificial intelligence. No part of Good Loop is generated, selected or assessed by an AI system, and no decision that affects you is taken by automated means." },
      { kind: "p", text: "We do not infer your emotions or intentions from your face, your voice or any other characteristic." },
      { kind: "p", text: "We do not use your content to train artificial intelligence models, and we do not allow any of our suppliers to do so." },
      { kind: "p", text: "If we introduce features that use artificial intelligence, we will tell you in advance, label them clearly wherever they appear, and publish an updated version of this notice before they go live." },
    ],
  },
  "D-07": {
    id: "D-07",
    title: "Professional independence",
    blocks: [
      { kind: "p", text: "Professionals working through Good Loop exercise independent professional judgement. Good Loop does not direct, instruct, review, override or second-guess a professional’s clinical decisions, and does not require a professional to apply the GL Methodology, or any particular technique within it, to any person." },
      { kind: "p", text: "A professional is required by their own regulator to assess whether a given approach and a given format are appropriate to the person in front of them, and to decline or to refer where they are not. Nothing in Good Loop’s platform, materials, training or commercial arrangements displaces that duty, and any suggestion, recommendation or prompt generated by the platform is advisory only and may be disregarded by the professional at their discretion." },
      { kind: "p", text: "Good Loop does not employ the professionals who deliver psychological services through the platform unless we expressly state otherwise in writing, and no agency, partnership or employment relationship is created by these Terms." },
      { kind: "p", text: "Good Loop does not recommend content, suggest an order of use, generate a plan, or vary what is available according to anything about a person. The library is the same for every professional. Selection, ordering, timing and interpretation are decisions of the professional alone." },
    ],
  },
  "D-08": {
    id: "D-08",
    title: "What your employer will never see",
    blocks: [
      { kind: "p", text: "Your employer, or whichever organisation is paying for your access to Good Loop, has bought a service for you. It has not bought information about you. This notice explains exactly what that organisation can and cannot learn, and it is a binding commitment, not a statement of intention." },
      { kind: "p", text: "Your sponsor will never receive, and we will never disclose to it:" },
      { kind: "p", text: "whether you have used Good Loop at all; when or how often you have used it; what content you have viewed or what exercises you have done; anything you have written, recorded or entered; whether you have booked, attended or missed a session; the identity of any professional you have worked with; anything discussed in a session; any assessment, note, record or observation about you; or any information from which any of the above could reasonably be worked out." },
      { kind: "h", text: "What your sponsor does receive" },
      { kind: "p", text: "Your sponsor receives information about the programme, not about people: aggregate figures on overall take-up and use across its whole population, and general reporting on the service. All such reporting is aggregated and de-identified, and we do not publish any figure derived from a group smaller than [twenty-five] individuals. Where a group is smaller than that threshold, the figure is suppressed rather than reported." },
      { kind: "h", text: "Sessions and clinical information" },
      { kind: "p", text: "Where a professional guides your use of Good Loop, what passes between you and that professional is covered by the professional’s duty of secrecy. It is not available to your sponsor in any form, in any circumstances, and no contract between Good Loop and your sponsor gives your sponsor any right to it." },
      { kind: "h", text: "Your sponsor’s obligations to you" },
      { kind: "p", text: "Our agreement with your sponsor requires it not to seek individual information about you from us, not to ask you to disclose your use of Good Loop, and not to treat you differently because you have used Good Loop or because you have not. If you believe that has happened, please tell us using the contact details in our Terms." },
      { kind: "h", text: "Ending or changing your sponsored access" },
      { kind: "p", text: "If your sponsor stops paying, or you leave the organisation, we will tell you before your access changes and we will explain what happens to your information and how you may continue independently where that option is available." },
    ],
  },
  "D-09": {
    id: "D-09",
    title: "Good Loop and your obligations as an employer",
    blocks: [
      { kind: "p", text: "Good Loop is a wellbeing service offered to your people. It is not a compliance product and it does not discharge any legal obligation that rests on you." },
      { kind: "p", text: "In particular, and without limitation: providing Good Loop does not identify, assess, evaluate, document or manage the psychosocial risk factors present in your organisation; it does not constitute or contribute to any risk inventory, risk management programme, action plan or risk assessment that you are required to prepare; it does not satisfy any obligation you may have in relation to occupational health and safety, working conditions or the organisation of work; and it is not evidence that any such obligation has been met." },
      { kind: "p", text: "Obligations of that kind concern the conditions and the organisation of work in your business. They are yours. They are not transferred to Good Loop by any agreement between us, and Good Loop assumes none of them." },
      { kind: "p", text: "Good Loop may form part of the support you choose to offer your people, and offering support of this kind may be one element among many in how you address wellbeing at work. Whether it is sufficient, and what else you must do, are matters for you and your own advisers." },
      { kind: "p", text: "Good Loop does not carry out individual clinical assessments of your employees, and does not provide you with information about any individual. Nothing in the service is designed or intended to be used as a mechanism for assessing psychosocial risk in your organisation." },
    ],
  },
  "D-10": {
    id: "D-10",
    title: "Confidentiality, your information and security",
    blocks: [
      { kind: "h", text: "Confidentiality" },
      { kind: "p", text: "What you tell a professional through Good Loop is confidential and is protected by that professional’s duty of secrecy under the rules of their profession. Good Loop treats information about your use of the platform as confidential and discloses it only as described in our Privacy Notice." },
      { kind: "h", text: "The limits of confidentiality" },
      { kind: "p", text: "Confidentiality is not absolute. A professional may be required by law or by the rules of their profession to disclose information in narrow circumstances — for example where there is a serious and imminent risk to your life or to the life of another person, where a child or a person at risk requires protection, or where a court or competent authority lawfully requires disclosure. Your professional will explain these limits to you as part of your informed consent, and will tell you wherever it is possible and appropriate to do so." },
      { kind: "h", text: "Recording" },
      { kind: "p", text: "You must not record, photograph, screenshot or otherwise capture any session, and you must not share any such recording. Professionals are subject to the same rule and may record only with your separate, specific and documented consent where their professional rules permit it." },
      { kind: "h", text: "Security" },
      { kind: "p", text: "We take the security of your information seriously and apply technical and organisational measures appropriate to its sensitivity, including encryption in transit and at rest, access controls limiting who within Good Loop can see what, logging of access, and regular review. We work only with suppliers who meet the standards we require." },
      { kind: "p", text: "No system connected to the internet can be guaranteed to be perfectly secure, and we cannot promise that. What we do promise is that we will maintain appropriate protection, that we will tell you and the competent authority if a security incident affects your information in a way that requires notification, and that we will tell you what happened and what we are doing about it." },
      { kind: "h", text: "Your part" },
      { kind: "p", text: "Please keep your access credentials secret, do not share your account, and use Good Loop in a private place where you can speak freely and where others cannot overhear or see your screen. Tell us immediately if you think someone else has accessed your account." },
    ],
  },
  "D-11": {
    id: "D-11",
    title: "Age",
    blocks: [
      { kind: "p", text: "Good Loop is offered only to people aged eighteen or over. It is not designed for, offered to, or suitable for children or adolescents, and it is not marketed to them." },
      { kind: "p", text: "By using Good Loop you confirm that you are eighteen or over and that you have the legal capacity to enter into these Terms." },
      { kind: "p", text: "If we learn that a person under eighteen has created an account, we will suspend the account, delete the personal data we hold about that person except where the law requires us to retain it, and, where the circumstances require it, take appropriate steps in relation to the safety of that person." },
    ],
  },
  "D-12": {
    id: "D-12",
    title: "Where Good Loop is offered",
    blocks: [
      { kind: "p", text: "Good Loop is offered only in the territories listed on our website. We do not offer Good Loop, and do not direct it, to people in any other territory." },
      { kind: "p", text: "Professionally guided services are subject to a further restriction. A professional may work with you through Good Loop only where that professional is registered and authorised to practise in the territory that applies to your situation, and only from a location from which they are permitted to practise. Where the applicable professional rules require a professional to be physically present in a particular territory, or to operate from a connection registered in it, the professional must comply with that requirement." },
      { kind: "p", text: "If you move to, or access Good Loop from, a territory in which we do not offer the service, some or all features may be unavailable to you, and professionally guided services in particular may be suspended until the position is clarified. This is a legal constraint, not a commercial choice." },
      { kind: "p", text: "You are responsible for complying with the law of the place from which you access Good Loop." },
    ],
  },
  "D-13": {
    id: "D-13",
    title: "What we can and cannot promise",
    blocks: [
      { kind: "p", text: "People respond differently to psychological wellbeing support. What helps one person may not help another, and progress is rarely linear. We do not promise any particular result from using Good Loop, and nobody honestly can." },
      { kind: "p", text: "We commit to providing the service with the care, skill and diligence that may reasonably be expected of a competent provider of a service of this kind, to describing what we offer accurately, and to correcting it when we get it wrong. We do not commit to any specific improvement in how you feel, to any outcome, or to any timescale, and no statement made by us, by any professional, or in any of our materials should be understood as such a commitment." },
      { kind: "p", text: "Where a professional guides your use of Good Loop, the professional’s obligation is likewise one of diligent professional care and not a guarantee of any clinical result." },
    ],
  },
  "D-14": {
    id: "D-14",
    title: "Content and services we do not control",
    blocks: [
      { kind: "p", text: "Good Loop may link to, or work with, websites, applications, resources and services operated by other organisations — including payment providers, communication tools, crisis and support organisations, and content produced by third parties. We do not control them and we are not responsible for them, for their content, for their terms, or for how they handle your information." },
      { kind: "p", text: "A link is not an endorsement, except where we expressly say that it is. Before using any third-party service, please read its own terms and privacy information." },
      { kind: "p", text: "Good Loop may also carry material contributed by users or by professionals. We do not review everything that is contributed before it appears. If you find content on Good Loop that is unlawful, harmful, or contrary to our rules, please report it using the contact details in our Terms. We will assess every report we receive and, where a report is well founded, we will remove or restrict access to the content and tell you what we have done." },
    ],
  },
  "D-15": {
    id: "D-15",
    title: "About what we say, and what others say, about Good Loop",
    blocks: [
      { kind: "p", text: "We describe Good Loop as a wellbeing service, because that is what it is. We do not claim that Good Loop treats, cures, prevents or reduces the symptoms of any illness, disorder or condition, and any statement that appears to make such a claim should be disregarded and reported to us." },
      { kind: "p", text: "Where we publish an account of one person’s experience, it is that person’s experience and nothing more. Individual experiences are not typical, are not evidence of what will happen for anyone else, and are not a promise of any result. Testimonials are published with the consent of the person concerned and may be edited for length; they are not paid for unless we say so." },
      { kind: "p", text: "Where we refer to research, we identify what the research was, what it measured and what its limits are. Research about a methodology, an approach or a population is not a statement about you." },
      { kind: "p", text: "We do describe our methodology as producing relaxation that is more efficient, and sessions that are well adapted to particular situations. Those are statements about how our methodology works, and we hold the evidence for them. They are not statements that Good Loop treats anything." },
    ],
  },
  "D-16": {
    id: "D-16",
    title: "Intellectual property",
    blocks: [
      { kind: "p", text: "The Good Loop platform, its content, its design, its software and the GL Methodology, together with all materials, protocols, exercises, instruments, sequences and documentation that express or embody the GL Methodology, are protected by copyright and by other intellectual property rights, and the confidential elements of the GL Methodology are protected as trade secrets. They belong to Good Loop or are used by Good Loop under licence. The GL Methodology was created by its intellectual author, whose authorship is recognised and preserved." },
      { kind: "p", text: "You are given a personal, limited, revocable, non-exclusive and non-transferable right to use Good Loop for your own use as permitted by these Terms. Nothing is assigned or licensed to you beyond that." },
      { kind: "p", text: "You must not copy, reproduce, adapt, translate, publish, distribute, sell, sublicense, publicly communicate or make available any part of the platform or of the GL Methodology; must not reverse engineer, decompile or attempt to derive the structure or logic of the platform or of the Methodology; must not use any part of the platform or of the Methodology to develop, train, evaluate or improve any competing product, model or service; and must not extract or scrape content from the platform by any means, automated or otherwise." },
      { kind: "p", text: "These restrictions continue to apply after you stop using Good Loop." },
    ],
  },
  "D-17": {
    id: "D-17",
    title: "In-product notices — core requirement",
    blocks: [
      { kind: "p", text: "Every screen of Good Loop gives one-tap access to emergency help through the Help now button, which shows emergency numbers before anything else." },
      { kind: "p", text: "The self-guided library states in one line that its sessions are for relaxation and are grouped by moment rather than by any condition. The first time a user opens each category, a short note restates this and, where relevant, points to professional help. Every self-guided session ends with a link to find a professional." },
      { kind: "p", text: "The full text of every notice is available one tap away and on the legal information page." },
      { kind: "p", text: "No notice is ever triggered by, varied by, or timed according to anything the user has entered, selected, rated, or been assessed on, or by any pattern in their use of the service. Notices appear at fixed moments — onboarding, checkout, booking, the first visit to a place, or a calendar date — on the same terms for every user." },
    ],
  },
  "terms": {
    id: "terms",
    title: "Terms and Conditions",
    blocks: [
      { kind: "p", text: "Version [1.0] — in force from [date]. Please read these Terms before using Good Loop. They set out what we agree to do, what we ask of you, and what happens if something goes wrong. Some of them limit what you can claim from us, and we have marked those clearly." },
      { kind: "h", text: "1. Who we are" },
      { kind: "p", text: "1.1 Good Loop is operated by [full corporate name], a company incorporated in [jurisdiction] under registration number [•], with its registered office at [•] (\"Good Loop\", \"we\", \"us\")." },
      { kind: "p", text: "1.2 You can contact us at [email], through the support function in the platform, or by writing to us at the address above. Our data protection officer can be reached at [email]." },
      { kind: "h", text: "2. These Terms and the documents that form part of them" },
      { kind: "p", text: "2.1 These Terms are a contract between you and us. By creating an account, or by using Good Loop, you accept them." },
      { kind: "p", text: "2.2 The following documents form part of these Terms and are available on our legal information page: the Platform Disclaimers (D-01 to D-16), the Privacy Notice, and any product-specific terms we present to you at the point of purchase. Where a summary of any of them differs from its full text, the full text applies." },
      { kind: "p", text: "2.3 If your access to Good Loop is paid for by an employer or another organisation, the End-User Supplement also applies to you and, on matters of sponsorship, prevails over these Terms." },
      { kind: "p", text: "2.4 Nothing in these Terms removes or limits any right you have under the consumer protection law of the country where you live. Where any provision of these Terms conflicts with such a right, that right applies and the provision does not." },
      { kind: "h", text: "3. Definitions" },
      { kind: "p", text: "3.1 In these Terms: \"Content\" means everything made available through Good Loop; \"GL Methodology\" means the proprietary psychological methodology described in our materials, together with everything that expresses or embodies it; \"Professional\" means a person licensed and registered to provide psychological services who offers those services through Good Loop; \"Professionally Guided Use\" means use of Good Loop where a Professional directs the application of the GL Methodology to you; \"Self-Guided Use\" means any other use; \"Service\" means the Good Loop platform and everything we provide through it; and \"Sponsor\" means an organisation that pays for your access." },
      { kind: "h", text: "4. Who may use Good Loop" },
      { kind: "p", text: "4.1 You must be eighteen or over and have the legal capacity to enter into these Terms. Good Loop is not offered to children or adolescents." },
      { kind: "p", text: "4.2 Good Loop is offered only in the territories listed on our website, and Professionally Guided Use is subject to the further restrictions in the Territorial Scope Notice (D-12)." },
      { kind: "p", text: "4.3 You may hold only one account, and it is personal to you. You must not share it, and you must not allow anyone else to use it." },
      { kind: "h", text: "5. Your account" },
      { kind: "p", text: "5.1 You must give us accurate information when you register and keep it up to date. Because Good Loop concerns your wellbeing, inaccurate information can lead to support that does not fit your situation." },
      { kind: "p", text: "5.2 Keep your credentials secret. Tell us immediately if you believe someone else has obtained access to your account, and we will help you secure it." },
      { kind: "p", text: "5.3 We may require additional verification where we reasonably need it — for example to confirm eligibility for a Sponsor’s programme." },
      { kind: "h", text: "6. What the Service is" },
      { kind: "p", text: "6.1 Good Loop is a digital platform for psychological wellbeing, offered in two distinct ways described in the Platform Disclaimers." },
      { kind: "p", text: "6.2 Self-Guided Use. When you use Good Loop without a Professional guiding you, the Service is a wellbeing service intended for relaxation, self-reflection and psychoeducation. It is not treatment, is not therapy, does not diagnose, and does not assess or manage any health condition. See D-02 and D-04." },
      { kind: "p", text: "6.3 Professionally Guided Use. Where a Professional works with you through Good Loop, that Professional provides the psychological service to you and holds the clinical relationship. We provide the platform, the GL Methodology and the environment. See D-05 and D-07." },
      { kind: "p", text: "6.4 Not an emergency service. Good Loop is not monitored in real time and must never be used in an emergency or where anyone is at risk. See D-03." },
      { kind: "p", text: "6.5 Good Loop does not currently include features that use artificial intelligence. If we introduce them, we will tell you in advance and the Automated Features Notice (D-06) will explain how they work." },
      { kind: "h", text: "7. Licence and intellectual property" },
      { kind: "p", text: "7.1 We give you a personal, limited, revocable, non-exclusive and non-transferable right to use the Service and access the Content for your own use in accordance with these Terms. That right ends when your access ends." },
      { kind: "p", text: "7.2 All rights in the Service, the Content and the GL Methodology remain with us or with our licensors, as set out in the Intellectual Property Notice (D-16). Nothing in these Terms transfers any of them to you." },
      { kind: "p", text: "7.3 You must not copy, adapt, distribute, sell, sublicense or publish any part of the Service or the GL Methodology; must not reverse engineer or attempt to derive its structure or logic; must not use any part of it to develop, train, evaluate or improve any competing product, model or service; and must not extract or scrape Content by any means. These restrictions survive termination." },
      { kind: "p", text: "7.4 If you contribute anything to the Service — a note, a message, feedback — you keep your rights in it. You give us a licence to host, store, transmit and display it strictly as needed to operate the Service for you and as described in our Privacy Notice. We do not use the content of your sessions with a Professional, or clinical information about you, to train artificial intelligence models." },
      { kind: "p", text: "7.5 Where you give us feedback about the Service, we may use it freely to improve the Service, without obligation to you." },
      { kind: "h", text: "8. Acceptable use" },
      { kind: "p", text: "8.1 You must use Good Loop lawfully, respectfully and for its intended purpose. In particular you must not:" },
      { kind: "li", text: "(a) use the Service to obtain a diagnosis, a prescription, a certification or any official determination;" },
      { kind: "li", text: "(b) impersonate anyone, or misrepresent your identity, age or eligibility;" },
      { kind: "li", text: "(c) record, photograph, screenshot or otherwise capture any session, or share any such recording;" },
      { kind: "li", text: "(d) harass, threaten, abuse or discriminate against any Professional, any member of our team or any other person;" },
      { kind: "li", text: "(e) upload or transmit anything unlawful, defamatory, or that infringes anyone’s rights;" },
      { kind: "li", text: "(f) attempt to gain unauthorised access to the Service, disrupt it, or introduce malicious code;" },
      { kind: "li", text: "(g) use automated means to access, extract from or interact with the Service without our written permission; or" },
      { kind: "li", text: "(h) resell, sublicense or commercially exploit the Service or any Content." },
      { kind: "p", text: "8.2 We may investigate suspected breaches and take proportionate action, which may include a warning, restriction of a feature, suspension or termination. Where we take action we will tell you why, unless the law prevents us." },
      { kind: "h", text: "9. Reporting content and our response" },
      { kind: "p", text: "9.1 If you find content on the Service that is unlawful, harmful or contrary to these Terms, please report it to [email] or through the reporting function. Tell us what the content is, where it is and why you are reporting it." },
      { kind: "p", text: "9.2 We will assess every report we receive. Where a report is well founded we will remove or restrict access to the content and take any further action that is appropriate. We will tell you the outcome and, where content of yours is removed, we will tell you why and how to contest that decision." },
      { kind: "p", text: "9.3 We keep a record of reports and of what we did about them." },
      { kind: "h", text: "10. Professionally guided services" },
      { kind: "p", text: "10.1 Where you book a Professional through Good Loop, a separate relationship arises between you and that Professional. Your informed consent and any terms agreed with the Professional govern that relationship and, on clinical matters, prevail over these Terms." },
      { kind: "p", text: "10.2 We verify at onboarding, and periodically thereafter, that each Professional holds a current registration with the relevant professional body. We do not warrant any Professional’s clinical skill, their suitability for you, or any outcome." },
      { kind: "p", text: "10.3 The Professional decides whether working with you at a distance is appropriate to your situation, and may decline or refer you elsewhere. That decision is theirs and we do not influence it." },
      { kind: "p", text: "10.4 Sessions must be attended at the scheduled time. Our cancellation and rescheduling rules for sessions are published in the platform and form part of these Terms; they apply equally to you and to the Professional." },
      { kind: "p", text: "10.5 If a Professional becomes unavailable, we will help you arrange an alternative where one is available. Where a therapeutic relationship is in progress, we will support an orderly handover in accordance with clause 15.4." },
      { kind: "h", text: "11. Prices, payment and subscriptions" },
      { kind: "p", text: "11.1 Prices are those shown at the time of purchase, in the currency stated, and include applicable taxes unless we say otherwise." },
      { kind: "p", text: "11.2 Where you buy a subscription, we will tell you clearly before you buy: what you get, the price, the billing period, that the subscription renews automatically, the price on renewal, and how to stop it. Your acceptance of automatic renewal is taken separately from your acceptance of these Terms." },
      { kind: "p", text: "11.3 A subscription renews automatically at the end of each billing period at the price then notified to you, unless you cancel before the renewal date. We will remind you before each renewal where the law requires it, and in any event before any renewal of a period longer than one month." },
      { kind: "p", text: "11.4 If we change the price of your subscription, we will tell you at least [thirty] days before the change takes effect and you may cancel before it does. A price change never applies to a period you have already paid for." },
      { kind: "p", text: "11.5 If a payment fails we will tell you and may suspend access until it is resolved. We will not terminate for a failed payment without giving you a reasonable opportunity to correct it." },
      { kind: "p", text: "11.6 Payments are processed by [payment provider]. Its own terms govern the processing of your payment, and we do not store your full card details." },
      { kind: "h", text: "12. Cancelling and changing your mind" },
      { kind: "p", text: "12.1 You may cancel a subscription at any time, effective at the end of the current billing period, through your account settings. Cancelling must never be harder than subscribing, and if you find that it is, tell us and we will cancel it for you." },
      { kind: "p", text: "12.2 Statutory right to change your mind. You have a statutory right to withdraw from a distance contract, in addition to the cancellation right in clause 12.1. The period and the way it works differ by country and are set out in the annex that applies to you:" },
      { kind: "li", text: "(a) if you live in Brazil, Annex I applies and the period is seven days; and" },
      { kind: "li", text: "(b) if you live in a Member State of the European Union, Annex II applies and the period is fourteen days." },
      { kind: "p", text: "Under Article 49 of the Consumer Protection Code, because you contracted outside our business premises, you may withdraw from this contract within seven days of the date you contracted or of the date you first accessed the Service, whichever is later, without giving any reason.", market: "BR" },
      { kind: "p", text: "To withdraw, tell us at [email] or through the platform. We will refund every amount you have paid, monetarily adjusted, immediately, using the same means of payment you used. You do not have to give a reason and we will not charge you anything for withdrawing.", market: "BR" },
      { kind: "p", text: "You have fourteen days from the day the contract is concluded to withdraw from it, without giving any reason.", market: "EU" },
      { kind: "p", text: "To withdraw, tell us by a clear statement — email to [email] is sufficient — or use the model withdrawal form available on our legal information page. It is enough that you send your notice before the fourteen days end.", market: "EU" },
      { kind: "p", text: "We will refund all payments received from you within fourteen days of being informed, using the same means of payment you used, at no cost to you.", market: "EU" },
      { kind: "p", text: "If you asked us to begin providing the Service during the withdrawal period and you then withdraw, you pay only an amount proportionate to what has been provided up to the moment you told us.", market: "EU" },
      { kind: "p", text: "12.3 To withdraw, tell us within the applicable period using any clear statement — email is sufficient — or the form provided in the relevant annex. We will refund what is due within the period stated in that annex, using the same means of payment you used." },
      { kind: "p", text: "12.4 Outside the statutory period, our refund policy published in the platform applies. That policy does not, and cannot, reduce your statutory rights." },
      { kind: "h", text: "13. Changes to the Service" },
      { kind: "p", text: "13.1 We improve the Service continually and may add, change or remove features. We will not make a change that materially reduces what you have paid for during a period you have already paid for." },
      { kind: "p", text: "13.2 If we make a change that materially and adversely affects you, we will tell you in advance and you may terminate and receive a pro-rata refund of any amount paid for the unexpired period." },
      { kind: "h", text: "14. Availability" },
      { kind: "p", text: "14.1 We work to keep the Service available but it may be interrupted for maintenance, for technical reasons, or by events outside our control. We will give notice of planned maintenance where we reasonably can." },
      { kind: "p", text: "14.2 The Service depends on your device, software and internet connection, which are your responsibility." },
      { kind: "h", text: "15. Suspension, termination and continuity" },
      { kind: "p", text: "15.1 You may close your account at any time." },
      { kind: "p", text: "15.2 We may suspend or terminate your access if you materially breach these Terms, if we are required to by law, or if continuing to provide the Service would expose you or another person to a serious risk. Except where the breach is serious or the law requires immediate action, we will give you notice and an opportunity to put things right." },
      { kind: "p", text: "15.3 On termination your right to use the Service ends. We will handle your personal data as described in our Privacy Notice and retain only what the law requires us to retain." },
      { kind: "p", text: "15.4 Continuity of care. Where a therapeutic relationship with a Professional is in progress and your access is about to end for any reason, we will tell you in advance, we will inform the Professional so that they can meet their own obligations to you, and we will support an orderly conclusion or handover. We will not terminate a therapeutic relationship abruptly where it is within our control to avoid doing so." },
      { kind: "p", text: "15.5 Clauses 7, 16, 17, 20, 23 and any other clause that by its nature should continue will survive termination." },
      { kind: "h", text: "16. Our responsibility to you" },
      { kind: "p", text: "We are responsible for providing the Service with the quality, security and suitability that you may properly expect, in accordance with the Consumer Protection Code. We do not exclude, reduce or transfer that responsibility, and nothing in these Terms should be read as attempting to do so.", market: "BR" },
      { kind: "p", text: "What we undertake to provide is described in clause 6 and in the Platform Disclaimers. In self-guided use we provide a wellbeing service; we do not provide treatment, diagnosis or clinical care, and we make no claim to do so. Where a Professional guides your use of Good Loop, that Professional provides the psychological service and is responsible for their own clinical acts, as described in D-05 and D-07, while we remain responsible for the platform operating and being secure as described and for verifying the Professional’s registration as described in clause 10.2.", market: "BR" },
      { kind: "p", text: "If the Service is defective, you have the rights given to you by the Consumer Protection Code, including repair of the defect, replacement of the service, a proportionate reduction of the price, or return of the amount paid, monetarily adjusted, together with compensation for any loss you suffer. Tell us at [email] and we will deal with it.", market: "BR" },
      { kind: "p", text: "16.1 We will provide the Service with reasonable care and skill.", market: "EU" },
      { kind: "p", text: "16.2 We are responsible for loss you suffer that is a foreseeable result of our breach of these Terms or our failure to use reasonable care and skill. We are not responsible for loss that is not foreseeable.", market: "EU" },
      { kind: "p", text: "16.3 We do not exclude or limit our liability in any way where it would be unlawful to do so. This includes liability for death or personal injury caused by our negligence, for fraud or fraudulent misrepresentation, for any breach of your statutory rights as a consumer, and for any liability that cannot be excluded under the data protection law that applies to you.", market: "EU" },
      { kind: "p", text: "16.4 Subject to clause 16.3, our total liability to you in connection with the Service in any twelve-month period is limited to the greater of the amount you paid us in that period and [EUR 500].", market: "EU" },
      { kind: "p", text: "16.5 We are not responsible for the clinical content, quality or outcome of what a Professional decides in your case, which is the Professional’s own responsibility as described in D-05 and D-07. This does not affect our responsibility for verifying registration as described in clause 10.2, or for the operation and security of the Service.", market: "EU" },
      { kind: "p", text: "16.6 We are not responsible for third-party websites, applications or services, as described in D-14.", market: "EU" },
      { kind: "p", text: "16.7 We supply the Service for personal use. We have no liability to you for loss of profit, loss of business, business interruption or loss of business opportunity.", market: "EU" },
      { kind: "h", text: "17. Your responsibility to us" },
      { kind: "p", text: "17.1 If you use the Service unlawfully, or in serious breach of clause 8, and we suffer loss as a result, you are responsible for that loss to the extent the law allows." },
      { kind: "h", text: "18. Your personal data" },
      { kind: "p", text: "18.1 We handle your personal data as described in our Privacy Notice, which forms part of these Terms." },
      { kind: "p", text: "18.2 Information about your mental health is sensitive and is treated as such. Where a Professional works with you, the clinical record is kept by that Professional under their own professional obligations, and we do not use it for our own purposes." },
      { kind: "p", text: "18.3 You have rights over your personal data, including rights of access, correction, deletion, portability and objection. The Privacy Notice explains how to exercise them and how to contact our data protection officer and, if you wish, the supervisory authority." },
      { kind: "h", text: "19. If something goes wrong" },
      { kind: "p", text: "19.1 Please tell us first. Write to [email] and we will acknowledge within [two] working days and respond substantively within [ten] working days, telling you what we have found and what we propose to do." },
      { kind: "p", text: "19.2 If you are not satisfied, you may take the matter further. Nothing in these Terms requires you to use our complaints process before exercising any legal right, and nothing in them requires you to arbitrate." },
      { kind: "p", text: "19.3 Where a complaint concerns the conduct of a Professional, you may also complain to that Professional’s professional body. We will give you its contact details on request." },
      { kind: "p", text: "19.4 The annex that applies to you identifies the consumer bodies and dispute resolution routes available in your country." },
      { kind: "h", text: "20. Governing law and where disputes are heard" },
      { kind: "p", text: "These Terms are governed by Brazilian law, in particular the Consumer Protection Code (Lei 8.078/1990), the General Data Protection Law (Lei 13.709/2018) and the Internet Civil Framework (Lei 12.965/2014).", market: "BR" },
      { kind: "p", text: "You may bring any proceedings in the court of your own domicile, and nothing in these Terms restricts that.", market: "BR" },
      { kind: "p", text: "These Terms contain no arbitration clause. You are not required to arbitrate any dispute with us, and nothing in these Terms waives your right to participate in a collective action.", market: "BR" },
      { kind: "p", text: "Before going to court you may, if you wish, use our complaints channel, contact the PROCON body for your state, or use the federal consumer platform at consumidor.gov.br. These are options available to you, not conditions you must satisfy.", market: "BR" },
      { kind: "p", text: "These Terms are governed by the law of the Member State in which you are habitually resident.", market: "EU" },
      { kind: "p", text: "You may bring proceedings in the courts of that Member State, and we will bring any proceedings against you only there.", market: "EU" },
      { kind: "p", text: "You may also use the European online dispute resolution platform or any alternative dispute resolution body applicable in your country. Details are on our legal information page. Using them is optional.", market: "EU" },
      { kind: "h", text: "21. Changes to these Terms" },
      { kind: "p", text: "21.1 We may change these Terms. We will tell you at least [thirty] days before a change that materially affects you takes effect, by email and in the platform, and we will publish what has changed." },
      { kind: "p", text: "21.2 If you do not accept a change you may terminate before it takes effect and receive a pro-rata refund of any amount paid for the unexpired period. Continuing to use the Service after the change takes effect means you accept it." },
      { kind: "p", text: "21.3 We keep previous versions of these Terms available on our legal information page, with the date each was in force." },
      { kind: "p", text: "21.4 We will not change these Terms retrospectively, and we will not change them unilaterally in a way that reduces what you have already paid for." },
      { kind: "h", text: "22. Transferring this agreement" },
      { kind: "p", text: "22.1 We may transfer our rights and obligations under these Terms to another organisation, for example on a reorganisation or sale of the business. We will tell you if we do, and the transfer will not reduce your rights. If you do not wish to continue, you may terminate and receive a pro-rata refund of any amount paid for the unexpired period." },
      { kind: "p", text: "22.2 You may not transfer your rights or obligations to anyone else." },
      { kind: "h", text: "23. General" },
      { kind: "p", text: "23.1 Severability. If any provision of these Terms is found to be invalid or unenforceable, the rest continue in force, and the invalid provision is replaced by a valid one that comes closest to its purpose." },
      { kind: "p", text: "23.2 No waiver. If we do not enforce a right immediately, we do not lose it." },
      { kind: "p", text: "23.3 Entire agreement. These Terms, together with the documents they incorporate, are the whole agreement between us about the Service. This does not exclude liability for anything we have said dishonestly, or affect statements that bind us under consumer law." },
      { kind: "p", text: "23.4 Language. These Terms are published in [Portuguese / Italian / English]. The [Portuguese] version governs for users in Brazil and the [Italian] version governs for users in Italy. Other language versions are provided for convenience." },
      { kind: "p", text: "23.5 Events outside our control. We are not responsible for failing to perform where the cause is outside our reasonable control, but we will tell you and we will not charge you for a service we cannot provide." },
      { kind: "p", text: "23.6 Version. This is version [1.0], in force from [date]." },
    ],
  },
  "supplement": {
    id: "supplement",
    title: "End-User Supplement — Sponsored Access",
    blocks: [
      { kind: "p", text: "S1.  Why you are reading this." },
      { kind: "p", text: "Your access to Good Loop is being paid for by your employer or another organisation (your \"Sponsor\"). This Supplement explains what that means. It adds to the Terms and Conditions, and where the two differ on anything to do with your Sponsor, this Supplement applies." },
      { kind: "p", text: "S2.  Your Sponsor is not a party to your use of Good Loop." },
      { kind: "p", text: "Your Sponsor has a commercial agreement with us. It is not a party to the agreement between you and us, and it has no rights over your account, your information or your care." },
      { kind: "p", text: "S3.  What your Sponsor never receives." },
      { kind: "p", text: "The Employer and Sponsor Confidentiality Notice (D-08) forms part of this Supplement and is a binding commitment we make to you. In summary: your Sponsor will never receive whether, when or how often you used Good Loop, what you did on it, anything you wrote, whether you booked or attended a session, who you saw, what was discussed, or anything from which any of that could reasonably be worked out." },
      { kind: "p", text: "S4.  What your Sponsor does receive." },
      { kind: "p", text: "Aggregated, de-identified information about the programme as a whole, never derived from a group smaller than [twenty-five] people. Figures below that threshold are suppressed, not reported." },
      { kind: "p", text: "S5.  Your Sponsor cannot ask you to give up this protection." },
      { kind: "p", text: "Our agreement with your Sponsor requires it not to seek individual information about you, not to ask you to disclose your use of Good Loop, and not to treat you differently because you have used it or because you have not. If you believe your Sponsor has done any of those things, please tell us at [email]. You may also raise it with the data protection authority in your country." },
      { kind: "p", text: "S6.  If sponsorship ends." },
      { kind: "p", text: "If your Sponsor stops paying, or you leave the organisation, we will give you at least [thirty] days’ notice before your access changes. We will tell you what happens to your information, and where a continuation option is available we will explain how to take it. If you are working with a Professional at that time, clause 15.4 of the Terms applies and we will support an orderly conclusion or handover." },
      { kind: "p", text: "S7.  Using Good Loop is your choice." },
      { kind: "p", text: "Your Sponsor may make Good Loop available to you, but it cannot require you to use it, and choosing not to use it is not a matter for your Sponsor." },
    ],
  },
  "professional": {
    id: "professional",
    title: "Professional Terms",
    blocks: [
      { kind: "h", text: "P1. Status and independence" },
      { kind: "p", text: "P1.1 The Professional is an independent provider, not an employee of Good Loop, and exercises independent professional judgement. No agency or partnership is created." },
      { kind: "p", text: "P1.2 Good Loop does not direct clinical decisions. Any suggestion generated by the platform, including by an automated feature, is advisory only and may be disregarded." },
      { kind: "h", text: "P2. Registration and competence" },
      { kind: "p", text: "P2.1 The Professional warrants that they hold a current registration with the relevant professional body, that they are authorised to practise in the territory from which they practise and in respect of the persons they serve, that no disciplinary proceedings are outstanding against them, and that they will notify Good Loop immediately if any of this changes." },
      { kind: "p", text: "P2.2 The Professional is responsible for assessing whether remote delivery, and the application of the GL Methodology, are appropriate to each person, and for declining or referring where they are not — consistent with CFP Resolution 9/2024 in Brazil and with the CNOP guidance in Italy." },
      { kind: "p", text: "P2.3 The Professional must comply with the territorial requirements of their professional rules, including any requirement to practise from within a particular territory or from a connection registered in it." },
      { kind: "p", text: "P2.4 Good Loop verifies registration at onboarding and periodically thereafter, and may suspend a Professional pending verification." },
      { kind: "h", text: "P3. Clinical responsibility and records" },
      { kind: "p", text: "P3.1 The Professional holds the clinical relationship and carries clinical and professional responsibility for it." },
      { kind: "p", text: "P3.2 The Professional is responsible for obtaining informed consent covering, at a minimum: the nature and purpose of the intervention; that it is delivered at a distance and what that means; the limits of the medium and what happens if the connection fails; confidentiality and its limits; how records are kept, where, for how long and who may access them; the arrangements if the person is at risk; fees and cancellation; and the alternatives to remote work. The Professional must document that consent." },
      { kind: "p", text: "P3.3 The Professional keeps the professional record required by their regulator and is the controller of it. Good Loop does not use it for its own purposes." },
      { kind: "p", text: "P3.4 The Professional must comply with Good Loop’s published escalation protocol where a person discloses risk, without prejudice to the Professional’s own professional judgement and duties, which prevail." },
      { kind: "p", text: "P3.5 Where a therapeutic relationship must end, the Professional must conclude or hand it over in accordance with their professional obligations, and must not discontinue abruptly." },
      { kind: "h", text: "P4. Methodology, confidentiality and intellectual property" },
      { kind: "p", text: "P4.1 The Professional is granted a limited, revocable, non-exclusive licence to use the Good Loop content library solely in the care they themselves provide through Good Loop, and for no other purpose. The Professional selects which content to use and when; Good Loop neither prescribes a sequence nor represents the library as a protocol or a course of treatment." },
      { kind: "p", text: "P4.2 The Professional must not disclose, reproduce, teach, publish or commercially exploit the GL Methodology; must not use it outside Good Loop; must not use it or any platform output to develop, train or evaluate any competing product, model or service; and must return or destroy all materials on termination. These obligations survive termination indefinitely as to confidential elements." },
      { kind: "p", text: "P4.3 The Professional must not record sessions except with the person’s separate documented consent where professional rules permit, and must not share any recording." },
      { kind: "p", text: "P4.4 The Professional must keep confidential all information about persons served and about Good Loop’s business." },
      { kind: "p", text: "P4.5 The Professional acknowledges that they are the sole treating party, that clinical judgement in whether and how to use the content is theirs, and that they will not describe Good Loop to any person they serve as the provider of treatment or as administering a therapeutic protocol." },
      { kind: "h", text: "P5. Insurance, indemnity and termination" },
      { kind: "p", text: "P5.1 The Professional must hold professional indemnity insurance of not less than [amount] and provide evidence on request." },
      { kind: "p", text: "P5.2 The Professional indemnifies Good Loop against claims arising from their clinical acts and omissions, from breach of these terms and from breach of their professional obligations." },
      { kind: "p", text: "P5.3 Good Loop may suspend or terminate immediately where registration lapses, where disciplinary proceedings are commenced, or where there is a serious risk to a person served — subject in every case to the continuity obligation in P3.5." },
    ],
  },
}
